// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ondewo/vtsi/events.proto
// </auto-generated>
// Original file comments:
// Copyright 2021 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Ondewo.Vtsi {
  /// <summary>
  /// &lt;p>ONDEWO VTSI API&lt;/p>
  /// &lt;p>Notifies other systems of VTSI events: calls, callers, listeners, scheduled callers,
  /// campaigns, VTSI projects, the project&amp;apos;s Asterisk and softphone accounts. Every event is one
  /// value of &lt;a href="index.html#ondewo.vtsi.VtsiEvent">VtsiEvent&lt;/a> and is delivered as a
  /// &lt;a href="index.html#ondewo.vtsi.VtsiEventMessage">VtsiEventMessage&lt;/a>.&lt;/p>
  /// &lt;p>Two delivery paths: the server-streaming &lt;code>SubscribeVtsiEvents&lt;/code> RPC, and WEBHOOKS
  /// (an HTTP request per event to a URL of the client&amp;apos;s choice). Which events go to which
  /// webhooks is configured per project with EVENT SUBSCRIPTIONS.&lt;/p>
  /// &lt;p>&lt;b>Webhooks are best effort.&lt;/b> Each event is sent to a webhook as at most
  /// &lt;code>ONDEWO_VTSI_WEBHOOK_MAX_ATTEMPTS&lt;/code> HTTP requests (3 by default) with backoff between
  /// them; after the last one fails, the event is dropped for that webhook. Pending webhook requests
  /// live in the memory of the server replica that produced the event and are lost when it restarts.
  /// An overloaded server, or a webhook that keeps timing out, drops events rather than slowing calls
  /// down. The same event can arrive more than once (a request whose answer was lost is sent again):
  /// de-duplicate by &lt;code>event_id&lt;/code>. Requests of one webhook can arrive out of order, because
  /// several server replicas send independently: order by &lt;code>resource_sequence&lt;/code> per
  /// &lt;code>resource_name&lt;/code>, then &lt;code>event_time&lt;/code>.&lt;/p>
  /// &lt;p>&lt;b>Streams can be resumed.&lt;/b> While a project has an open &lt;code>SubscribeVtsiEvents&lt;/code>
  /// stream or an enabled event subscription, its events are also written to a short-lived journal
  /// (24 h by default). A stream that reconnects with its last &lt;code>resume_token&lt;/code> receives the
  /// events it missed, provided they are still in the journal; nothing else is persisted for
  /// redelivery.&lt;/p>
  /// &lt;p>Use the status RPCs (&lt;code>GetCampaign&lt;/code>, &lt;code>ListCalls&lt;/code>, the status streams) to
  /// reconcile.&lt;/p>
  /// &lt;p>&lt;b>Custom header values are write-only.&lt;/b> They are returned as &lt;code>********&lt;/code> by every
  /// RPC and are never logged.&lt;/p>
  /// &lt;p>Errors are gRPC status codes: &lt;code>INVALID_ARGUMENT&lt;/code>, &lt;code>NOT_FOUND&lt;/code>,
  /// &lt;code>FAILED_PRECONDITION&lt;/code>, &lt;code>RESOURCE_EXHAUSTED&lt;/code> (no free stream slot).&lt;/p>
  /// </summary>
  public static partial class Events
  {
    static readonly string __ServiceName = "ondewo.vtsi.Events";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.CreateVtsiEventSubscriptionRequest> __Marshaller_ondewo_vtsi_CreateVtsiEventSubscriptionRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.CreateVtsiEventSubscriptionRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.VtsiEventSubscription> __Marshaller_ondewo_vtsi_VtsiEventSubscription = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.VtsiEventSubscription.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.GetVtsiEventSubscriptionRequest> __Marshaller_ondewo_vtsi_GetVtsiEventSubscriptionRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.GetVtsiEventSubscriptionRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.UpdateVtsiEventSubscriptionRequest> __Marshaller_ondewo_vtsi_UpdateVtsiEventSubscriptionRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.UpdateVtsiEventSubscriptionRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.DeleteVtsiEventSubscriptionRequest> __Marshaller_ondewo_vtsi_DeleteVtsiEventSubscriptionRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.DeleteVtsiEventSubscriptionRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.DeleteVtsiEventSubscriptionResponse> __Marshaller_ondewo_vtsi_DeleteVtsiEventSubscriptionResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.DeleteVtsiEventSubscriptionResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.ListVtsiEventSubscriptionsRequest> __Marshaller_ondewo_vtsi_ListVtsiEventSubscriptionsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.ListVtsiEventSubscriptionsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.ListVtsiEventSubscriptionsResponse> __Marshaller_ondewo_vtsi_ListVtsiEventSubscriptionsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.ListVtsiEventSubscriptionsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.CreateWebhookRequest> __Marshaller_ondewo_vtsi_CreateWebhookRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.CreateWebhookRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.Webhook> __Marshaller_ondewo_vtsi_Webhook = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.Webhook.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.GetWebhookRequest> __Marshaller_ondewo_vtsi_GetWebhookRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.GetWebhookRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.UpdateWebhookRequest> __Marshaller_ondewo_vtsi_UpdateWebhookRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.UpdateWebhookRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.DeleteWebhookRequest> __Marshaller_ondewo_vtsi_DeleteWebhookRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.DeleteWebhookRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.DeleteWebhookResponse> __Marshaller_ondewo_vtsi_DeleteWebhookResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.DeleteWebhookResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.ListWebhooksRequest> __Marshaller_ondewo_vtsi_ListWebhooksRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.ListWebhooksRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.ListWebhooksResponse> __Marshaller_ondewo_vtsi_ListWebhooksResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.ListWebhooksResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.TestWebhookRequest> __Marshaller_ondewo_vtsi_TestWebhookRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.TestWebhookRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.TestWebhookResponse> __Marshaller_ondewo_vtsi_TestWebhookResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.TestWebhookResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.SubscribeVtsiEventsRequest> __Marshaller_ondewo_vtsi_SubscribeVtsiEventsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.SubscribeVtsiEventsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.SubscribeVtsiEventsResponse> __Marshaller_ondewo_vtsi_SubscribeVtsiEventsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.SubscribeVtsiEventsResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Vtsi.CreateVtsiEventSubscriptionRequest, global::Ondewo.Vtsi.VtsiEventSubscription> __Method_CreateVtsiEventSubscription = new grpc::Method<global::Ondewo.Vtsi.CreateVtsiEventSubscriptionRequest, global::Ondewo.Vtsi.VtsiEventSubscription>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateVtsiEventSubscription",
        __Marshaller_ondewo_vtsi_CreateVtsiEventSubscriptionRequest,
        __Marshaller_ondewo_vtsi_VtsiEventSubscription);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Vtsi.GetVtsiEventSubscriptionRequest, global::Ondewo.Vtsi.VtsiEventSubscription> __Method_GetVtsiEventSubscription = new grpc::Method<global::Ondewo.Vtsi.GetVtsiEventSubscriptionRequest, global::Ondewo.Vtsi.VtsiEventSubscription>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetVtsiEventSubscription",
        __Marshaller_ondewo_vtsi_GetVtsiEventSubscriptionRequest,
        __Marshaller_ondewo_vtsi_VtsiEventSubscription);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Vtsi.UpdateVtsiEventSubscriptionRequest, global::Ondewo.Vtsi.VtsiEventSubscription> __Method_UpdateVtsiEventSubscription = new grpc::Method<global::Ondewo.Vtsi.UpdateVtsiEventSubscriptionRequest, global::Ondewo.Vtsi.VtsiEventSubscription>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateVtsiEventSubscription",
        __Marshaller_ondewo_vtsi_UpdateVtsiEventSubscriptionRequest,
        __Marshaller_ondewo_vtsi_VtsiEventSubscription);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Vtsi.DeleteVtsiEventSubscriptionRequest, global::Ondewo.Vtsi.DeleteVtsiEventSubscriptionResponse> __Method_DeleteVtsiEventSubscription = new grpc::Method<global::Ondewo.Vtsi.DeleteVtsiEventSubscriptionRequest, global::Ondewo.Vtsi.DeleteVtsiEventSubscriptionResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteVtsiEventSubscription",
        __Marshaller_ondewo_vtsi_DeleteVtsiEventSubscriptionRequest,
        __Marshaller_ondewo_vtsi_DeleteVtsiEventSubscriptionResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Vtsi.ListVtsiEventSubscriptionsRequest, global::Ondewo.Vtsi.ListVtsiEventSubscriptionsResponse> __Method_ListVtsiEventSubscriptions = new grpc::Method<global::Ondewo.Vtsi.ListVtsiEventSubscriptionsRequest, global::Ondewo.Vtsi.ListVtsiEventSubscriptionsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListVtsiEventSubscriptions",
        __Marshaller_ondewo_vtsi_ListVtsiEventSubscriptionsRequest,
        __Marshaller_ondewo_vtsi_ListVtsiEventSubscriptionsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Vtsi.CreateWebhookRequest, global::Ondewo.Vtsi.Webhook> __Method_CreateWebhook = new grpc::Method<global::Ondewo.Vtsi.CreateWebhookRequest, global::Ondewo.Vtsi.Webhook>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CreateWebhook",
        __Marshaller_ondewo_vtsi_CreateWebhookRequest,
        __Marshaller_ondewo_vtsi_Webhook);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Vtsi.GetWebhookRequest, global::Ondewo.Vtsi.Webhook> __Method_GetWebhook = new grpc::Method<global::Ondewo.Vtsi.GetWebhookRequest, global::Ondewo.Vtsi.Webhook>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetWebhook",
        __Marshaller_ondewo_vtsi_GetWebhookRequest,
        __Marshaller_ondewo_vtsi_Webhook);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Vtsi.UpdateWebhookRequest, global::Ondewo.Vtsi.Webhook> __Method_UpdateWebhook = new grpc::Method<global::Ondewo.Vtsi.UpdateWebhookRequest, global::Ondewo.Vtsi.Webhook>(
        grpc::MethodType.Unary,
        __ServiceName,
        "UpdateWebhook",
        __Marshaller_ondewo_vtsi_UpdateWebhookRequest,
        __Marshaller_ondewo_vtsi_Webhook);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Vtsi.DeleteWebhookRequest, global::Ondewo.Vtsi.DeleteWebhookResponse> __Method_DeleteWebhook = new grpc::Method<global::Ondewo.Vtsi.DeleteWebhookRequest, global::Ondewo.Vtsi.DeleteWebhookResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteWebhook",
        __Marshaller_ondewo_vtsi_DeleteWebhookRequest,
        __Marshaller_ondewo_vtsi_DeleteWebhookResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Vtsi.ListWebhooksRequest, global::Ondewo.Vtsi.ListWebhooksResponse> __Method_ListWebhooks = new grpc::Method<global::Ondewo.Vtsi.ListWebhooksRequest, global::Ondewo.Vtsi.ListWebhooksResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListWebhooks",
        __Marshaller_ondewo_vtsi_ListWebhooksRequest,
        __Marshaller_ondewo_vtsi_ListWebhooksResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Vtsi.TestWebhookRequest, global::Ondewo.Vtsi.TestWebhookResponse> __Method_TestWebhook = new grpc::Method<global::Ondewo.Vtsi.TestWebhookRequest, global::Ondewo.Vtsi.TestWebhookResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "TestWebhook",
        __Marshaller_ondewo_vtsi_TestWebhookRequest,
        __Marshaller_ondewo_vtsi_TestWebhookResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Vtsi.SubscribeVtsiEventsRequest, global::Ondewo.Vtsi.SubscribeVtsiEventsResponse> __Method_SubscribeVtsiEvents = new grpc::Method<global::Ondewo.Vtsi.SubscribeVtsiEventsRequest, global::Ondewo.Vtsi.SubscribeVtsiEventsResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "SubscribeVtsiEvents",
        __Marshaller_ondewo_vtsi_SubscribeVtsiEventsRequest,
        __Marshaller_ondewo_vtsi_SubscribeVtsiEventsResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Ondewo.Vtsi.EventsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Events</summary>
    [grpc::BindServiceMethod(typeof(Events), "BindService")]
    public abstract partial class EventsBase
    {
      /// <summary>
      /// &lt;p>Creates an event subscription: which events of the project are delivered to which
      /// webhooks. A subscription without webhooks is usable by &lt;code>SubscribeVtsiEvents&lt;/code>.&lt;/p>
      /// &lt;p>Errors: &lt;code>NOT_FOUND&lt;/code> for an unknown project or webhook; &lt;code>INVALID_ARGUMENT&lt;/code>
      /// for no events and &lt;code>all_events&lt;/code> unset, &lt;code>events&lt;/code> together with
      /// &lt;code>all_events&lt;/code>, &lt;code>VTSI_EVENT_UNSPECIFIED&lt;/code> or a reserved value, a webhook or a
      /// campaign name of another project, a malformed campaign name, or an output-only field that was
      /// set. A campaign named in &lt;code>campaign_names&lt;/code> need not exist (it may be created later
      /// or deleted since).&lt;/p>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Vtsi.VtsiEventSubscription> CreateVtsiEventSubscription(global::Ondewo.Vtsi.CreateVtsiEventSubscriptionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>Returns an event subscription.&lt;/p>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Vtsi.VtsiEventSubscription> GetVtsiEventSubscription(global::Ondewo.Vtsi.GetVtsiEventSubscriptionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>Updates the fields named in &lt;code>update_mask&lt;/code>: &lt;code>display_name&lt;/code>,
      /// &lt;code>events&lt;/code>, &lt;code>all_events&lt;/code>, &lt;code>resource_name_prefixes&lt;/code>,
      /// &lt;code>campaign_names&lt;/code>, &lt;code>webhook_names&lt;/code>, &lt;code>disabled&lt;/code>. Takes effect
      /// within a few seconds on every server replica.&lt;/p>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Vtsi.VtsiEventSubscription> UpdateVtsiEventSubscription(global::Ondewo.Vtsi.UpdateVtsiEventSubscriptionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>Deletes an event subscription. Open &lt;code>SubscribeVtsiEvents&lt;/code> streams that name it
      /// end with &lt;code>end_reason&lt;/code> set.&lt;/p>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Vtsi.DeleteVtsiEventSubscriptionResponse> DeleteVtsiEventSubscription(global::Ondewo.Vtsi.DeleteVtsiEventSubscriptionRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>Lists the event subscriptions of a project, paged.&lt;/p>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Vtsi.ListVtsiEventSubscriptionsResponse> ListVtsiEventSubscriptions(global::Ondewo.Vtsi.ListVtsiEventSubscriptionsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>Creates a webhook: an HTTP(S) endpoint that receives one request per event, with a JSON
      /// body holding the &lt;code>VtsiEventMessage&lt;/code> (proto3 JSON, original field names).&lt;/p>
      /// &lt;p>Errors: &lt;code>NOT_FOUND&lt;/code> for an unknown project; &lt;code>INVALID_ARGUMENT&lt;/code> for a
      /// URL that is not http(s), has no host, carries user information (use a custom header for
      /// credentials) or exceeds 2048 characters; for a reserved or malformed header name, a header
      /// value with a line break, too many or too long headers; or for a timeout outside
      /// 1 s to 30 s.&lt;/p>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Vtsi.Webhook> CreateWebhook(global::Ondewo.Vtsi.CreateWebhookRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>Returns a webhook. Custom header values are masked.&lt;/p>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Vtsi.Webhook> GetWebhook(global::Ondewo.Vtsi.GetWebhookRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>Updates the fields named in &lt;code>update_mask&lt;/code>: &lt;code>display_name&lt;/code>,
      /// &lt;code>url&lt;/code>, &lt;code>http_method&lt;/code>, &lt;code>custom_headers&lt;/code>, &lt;code>disabled&lt;/code>,
      /// &lt;code>timeout&lt;/code>. &lt;code>custom_headers&lt;/code> replaces the whole map; a value equal to the
      /// mask &lt;code>********&lt;/code> keeps the stored value of that header, so a Get-modify-Update
      /// round trip does not overwrite secrets with the mask.&lt;/p>
      /// &lt;p>Moving the webhook to another origin (scheme, host or port of &lt;code>url&lt;/code>) while custom
      /// headers are stored requires re-sending &lt;code>custom_headers&lt;/code> in the same request, with
      /// their REAL values (or an empty map to drop them): the stored values are never carried to a new
      /// origin, and an update that leaves &lt;code>custom_headers&lt;/code> out of the mask or sends the mask
      /// value &lt;code>********&lt;/code> for any header is rejected with &lt;code>INVALID_ARGUMENT&lt;/code> naming
      /// the headers. A new path on the same origin keeps the stored values.&lt;/p>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Vtsi.Webhook> UpdateWebhook(global::Ondewo.Vtsi.UpdateWebhookRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>Deletes a webhook and removes it from every event subscription.&lt;/p>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Vtsi.DeleteWebhookResponse> DeleteWebhook(global::Ondewo.Vtsi.DeleteWebhookRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>Lists the webhooks of a project, paged. Custom header values are masked.&lt;/p>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Vtsi.ListWebhooksResponse> ListWebhooks(global::Ondewo.Vtsi.ListWebhooksRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>Sends one &lt;code>VTSI_EVENT_WEBHOOK_TEST&lt;/code> event to a webhook now, without retries,
      /// and reports the outcome. Works on a disabled webhook too, and ignores an open circuit.&lt;/p>
      /// &lt;p>Errors: &lt;code>NOT_FOUND&lt;/code>. A failed delivery is reported in the response, not as an
      /// error status.&lt;/p>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Vtsi.TestWebhookResponse> TestWebhook(global::Ondewo.Vtsi.TestWebhookRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>Streams the events of a project as they happen, selected either by a named event
      /// subscription or by an inline filter. An empty message is sent as a keep-alive. After a
      /// disconnect, pass the last &lt;code>resume_token&lt;/code> to continue where the stream stopped;
      /// events older than the server&amp;apos;s retention (24 h by default) are no longer available, and
      /// the journal records a project&amp;apos;s events only while it has an open stream (and for 1 h
      /// after the last one closed) or an enabled event subscription. A stream sees events of other
      /// server replicas from at most a few seconds after it opened. A client that stops reading for
      /// longer than the server&amp;apos;s stall timeout (30 s by default) is disconnected; reconnect with
      /// the &lt;code>resume_token&lt;/code>. When the project is deleted, the stream delivers
      /// &lt;code>VTSI_EVENT_VTSI_PROJECT_DELETED&lt;/code> and ends.&lt;/p>
      /// &lt;p>Errors: &lt;code>NOT_FOUND&lt;/code> for an unknown project or subscription;
      /// &lt;code>INVALID_ARGUMENT&lt;/code> for a malformed &lt;code>resume_token&lt;/code>;
      /// &lt;code>FAILED_PRECONDITION&lt;/code> for a disabled subscription; &lt;code>RESOURCE_EXHAUSTED&lt;/code>
      /// when the server has no free stream slot.&lt;/p>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task SubscribeVtsiEvents(global::Ondewo.Vtsi.SubscribeVtsiEventsRequest request, grpc::IServerStreamWriter<global::Ondewo.Vtsi.SubscribeVtsiEventsResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Events</summary>
    public partial class EventsClient : grpc::ClientBase<EventsClient>
    {
      /// <summary>Creates a new client for Events</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public EventsClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Events that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public EventsClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected EventsClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected EventsClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// &lt;p>Creates an event subscription: which events of the project are delivered to which
      /// webhooks. A subscription without webhooks is usable by &lt;code>SubscribeVtsiEvents&lt;/code>.&lt;/p>
      /// &lt;p>Errors: &lt;code>NOT_FOUND&lt;/code> for an unknown project or webhook; &lt;code>INVALID_ARGUMENT&lt;/code>
      /// for no events and &lt;code>all_events&lt;/code> unset, &lt;code>events&lt;/code> together with
      /// &lt;code>all_events&lt;/code>, &lt;code>VTSI_EVENT_UNSPECIFIED&lt;/code> or a reserved value, a webhook or a
      /// campaign name of another project, a malformed campaign name, or an output-only field that was
      /// set. A campaign named in &lt;code>campaign_names&lt;/code> need not exist (it may be created later
      /// or deleted since).&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.VtsiEventSubscription CreateVtsiEventSubscription(global::Ondewo.Vtsi.CreateVtsiEventSubscriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateVtsiEventSubscription(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Creates an event subscription: which events of the project are delivered to which
      /// webhooks. A subscription without webhooks is usable by &lt;code>SubscribeVtsiEvents&lt;/code>.&lt;/p>
      /// &lt;p>Errors: &lt;code>NOT_FOUND&lt;/code> for an unknown project or webhook; &lt;code>INVALID_ARGUMENT&lt;/code>
      /// for no events and &lt;code>all_events&lt;/code> unset, &lt;code>events&lt;/code> together with
      /// &lt;code>all_events&lt;/code>, &lt;code>VTSI_EVENT_UNSPECIFIED&lt;/code> or a reserved value, a webhook or a
      /// campaign name of another project, a malformed campaign name, or an output-only field that was
      /// set. A campaign named in &lt;code>campaign_names&lt;/code> need not exist (it may be created later
      /// or deleted since).&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.VtsiEventSubscription CreateVtsiEventSubscription(global::Ondewo.Vtsi.CreateVtsiEventSubscriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateVtsiEventSubscription, null, options, request);
      }
      /// <summary>
      /// &lt;p>Creates an event subscription: which events of the project are delivered to which
      /// webhooks. A subscription without webhooks is usable by &lt;code>SubscribeVtsiEvents&lt;/code>.&lt;/p>
      /// &lt;p>Errors: &lt;code>NOT_FOUND&lt;/code> for an unknown project or webhook; &lt;code>INVALID_ARGUMENT&lt;/code>
      /// for no events and &lt;code>all_events&lt;/code> unset, &lt;code>events&lt;/code> together with
      /// &lt;code>all_events&lt;/code>, &lt;code>VTSI_EVENT_UNSPECIFIED&lt;/code> or a reserved value, a webhook or a
      /// campaign name of another project, a malformed campaign name, or an output-only field that was
      /// set. A campaign named in &lt;code>campaign_names&lt;/code> need not exist (it may be created later
      /// or deleted since).&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.VtsiEventSubscription> CreateVtsiEventSubscriptionAsync(global::Ondewo.Vtsi.CreateVtsiEventSubscriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateVtsiEventSubscriptionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Creates an event subscription: which events of the project are delivered to which
      /// webhooks. A subscription without webhooks is usable by &lt;code>SubscribeVtsiEvents&lt;/code>.&lt;/p>
      /// &lt;p>Errors: &lt;code>NOT_FOUND&lt;/code> for an unknown project or webhook; &lt;code>INVALID_ARGUMENT&lt;/code>
      /// for no events and &lt;code>all_events&lt;/code> unset, &lt;code>events&lt;/code> together with
      /// &lt;code>all_events&lt;/code>, &lt;code>VTSI_EVENT_UNSPECIFIED&lt;/code> or a reserved value, a webhook or a
      /// campaign name of another project, a malformed campaign name, or an output-only field that was
      /// set. A campaign named in &lt;code>campaign_names&lt;/code> need not exist (it may be created later
      /// or deleted since).&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.VtsiEventSubscription> CreateVtsiEventSubscriptionAsync(global::Ondewo.Vtsi.CreateVtsiEventSubscriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateVtsiEventSubscription, null, options, request);
      }
      /// <summary>
      /// &lt;p>Returns an event subscription.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.VtsiEventSubscription GetVtsiEventSubscription(global::Ondewo.Vtsi.GetVtsiEventSubscriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetVtsiEventSubscription(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Returns an event subscription.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.VtsiEventSubscription GetVtsiEventSubscription(global::Ondewo.Vtsi.GetVtsiEventSubscriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetVtsiEventSubscription, null, options, request);
      }
      /// <summary>
      /// &lt;p>Returns an event subscription.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.VtsiEventSubscription> GetVtsiEventSubscriptionAsync(global::Ondewo.Vtsi.GetVtsiEventSubscriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetVtsiEventSubscriptionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Returns an event subscription.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.VtsiEventSubscription> GetVtsiEventSubscriptionAsync(global::Ondewo.Vtsi.GetVtsiEventSubscriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetVtsiEventSubscription, null, options, request);
      }
      /// <summary>
      /// &lt;p>Updates the fields named in &lt;code>update_mask&lt;/code>: &lt;code>display_name&lt;/code>,
      /// &lt;code>events&lt;/code>, &lt;code>all_events&lt;/code>, &lt;code>resource_name_prefixes&lt;/code>,
      /// &lt;code>campaign_names&lt;/code>, &lt;code>webhook_names&lt;/code>, &lt;code>disabled&lt;/code>. Takes effect
      /// within a few seconds on every server replica.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.VtsiEventSubscription UpdateVtsiEventSubscription(global::Ondewo.Vtsi.UpdateVtsiEventSubscriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateVtsiEventSubscription(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Updates the fields named in &lt;code>update_mask&lt;/code>: &lt;code>display_name&lt;/code>,
      /// &lt;code>events&lt;/code>, &lt;code>all_events&lt;/code>, &lt;code>resource_name_prefixes&lt;/code>,
      /// &lt;code>campaign_names&lt;/code>, &lt;code>webhook_names&lt;/code>, &lt;code>disabled&lt;/code>. Takes effect
      /// within a few seconds on every server replica.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.VtsiEventSubscription UpdateVtsiEventSubscription(global::Ondewo.Vtsi.UpdateVtsiEventSubscriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateVtsiEventSubscription, null, options, request);
      }
      /// <summary>
      /// &lt;p>Updates the fields named in &lt;code>update_mask&lt;/code>: &lt;code>display_name&lt;/code>,
      /// &lt;code>events&lt;/code>, &lt;code>all_events&lt;/code>, &lt;code>resource_name_prefixes&lt;/code>,
      /// &lt;code>campaign_names&lt;/code>, &lt;code>webhook_names&lt;/code>, &lt;code>disabled&lt;/code>. Takes effect
      /// within a few seconds on every server replica.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.VtsiEventSubscription> UpdateVtsiEventSubscriptionAsync(global::Ondewo.Vtsi.UpdateVtsiEventSubscriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateVtsiEventSubscriptionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Updates the fields named in &lt;code>update_mask&lt;/code>: &lt;code>display_name&lt;/code>,
      /// &lt;code>events&lt;/code>, &lt;code>all_events&lt;/code>, &lt;code>resource_name_prefixes&lt;/code>,
      /// &lt;code>campaign_names&lt;/code>, &lt;code>webhook_names&lt;/code>, &lt;code>disabled&lt;/code>. Takes effect
      /// within a few seconds on every server replica.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.VtsiEventSubscription> UpdateVtsiEventSubscriptionAsync(global::Ondewo.Vtsi.UpdateVtsiEventSubscriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateVtsiEventSubscription, null, options, request);
      }
      /// <summary>
      /// &lt;p>Deletes an event subscription. Open &lt;code>SubscribeVtsiEvents&lt;/code> streams that name it
      /// end with &lt;code>end_reason&lt;/code> set.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.DeleteVtsiEventSubscriptionResponse DeleteVtsiEventSubscription(global::Ondewo.Vtsi.DeleteVtsiEventSubscriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteVtsiEventSubscription(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Deletes an event subscription. Open &lt;code>SubscribeVtsiEvents&lt;/code> streams that name it
      /// end with &lt;code>end_reason&lt;/code> set.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.DeleteVtsiEventSubscriptionResponse DeleteVtsiEventSubscription(global::Ondewo.Vtsi.DeleteVtsiEventSubscriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteVtsiEventSubscription, null, options, request);
      }
      /// <summary>
      /// &lt;p>Deletes an event subscription. Open &lt;code>SubscribeVtsiEvents&lt;/code> streams that name it
      /// end with &lt;code>end_reason&lt;/code> set.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.DeleteVtsiEventSubscriptionResponse> DeleteVtsiEventSubscriptionAsync(global::Ondewo.Vtsi.DeleteVtsiEventSubscriptionRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteVtsiEventSubscriptionAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Deletes an event subscription. Open &lt;code>SubscribeVtsiEvents&lt;/code> streams that name it
      /// end with &lt;code>end_reason&lt;/code> set.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.DeleteVtsiEventSubscriptionResponse> DeleteVtsiEventSubscriptionAsync(global::Ondewo.Vtsi.DeleteVtsiEventSubscriptionRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteVtsiEventSubscription, null, options, request);
      }
      /// <summary>
      /// &lt;p>Lists the event subscriptions of a project, paged.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.ListVtsiEventSubscriptionsResponse ListVtsiEventSubscriptions(global::Ondewo.Vtsi.ListVtsiEventSubscriptionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListVtsiEventSubscriptions(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Lists the event subscriptions of a project, paged.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.ListVtsiEventSubscriptionsResponse ListVtsiEventSubscriptions(global::Ondewo.Vtsi.ListVtsiEventSubscriptionsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListVtsiEventSubscriptions, null, options, request);
      }
      /// <summary>
      /// &lt;p>Lists the event subscriptions of a project, paged.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.ListVtsiEventSubscriptionsResponse> ListVtsiEventSubscriptionsAsync(global::Ondewo.Vtsi.ListVtsiEventSubscriptionsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListVtsiEventSubscriptionsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Lists the event subscriptions of a project, paged.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.ListVtsiEventSubscriptionsResponse> ListVtsiEventSubscriptionsAsync(global::Ondewo.Vtsi.ListVtsiEventSubscriptionsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListVtsiEventSubscriptions, null, options, request);
      }
      /// <summary>
      /// &lt;p>Creates a webhook: an HTTP(S) endpoint that receives one request per event, with a JSON
      /// body holding the &lt;code>VtsiEventMessage&lt;/code> (proto3 JSON, original field names).&lt;/p>
      /// &lt;p>Errors: &lt;code>NOT_FOUND&lt;/code> for an unknown project; &lt;code>INVALID_ARGUMENT&lt;/code> for a
      /// URL that is not http(s), has no host, carries user information (use a custom header for
      /// credentials) or exceeds 2048 characters; for a reserved or malformed header name, a header
      /// value with a line break, too many or too long headers; or for a timeout outside
      /// 1 s to 30 s.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.Webhook CreateWebhook(global::Ondewo.Vtsi.CreateWebhookRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateWebhook(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Creates a webhook: an HTTP(S) endpoint that receives one request per event, with a JSON
      /// body holding the &lt;code>VtsiEventMessage&lt;/code> (proto3 JSON, original field names).&lt;/p>
      /// &lt;p>Errors: &lt;code>NOT_FOUND&lt;/code> for an unknown project; &lt;code>INVALID_ARGUMENT&lt;/code> for a
      /// URL that is not http(s), has no host, carries user information (use a custom header for
      /// credentials) or exceeds 2048 characters; for a reserved or malformed header name, a header
      /// value with a line break, too many or too long headers; or for a timeout outside
      /// 1 s to 30 s.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.Webhook CreateWebhook(global::Ondewo.Vtsi.CreateWebhookRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CreateWebhook, null, options, request);
      }
      /// <summary>
      /// &lt;p>Creates a webhook: an HTTP(S) endpoint that receives one request per event, with a JSON
      /// body holding the &lt;code>VtsiEventMessage&lt;/code> (proto3 JSON, original field names).&lt;/p>
      /// &lt;p>Errors: &lt;code>NOT_FOUND&lt;/code> for an unknown project; &lt;code>INVALID_ARGUMENT&lt;/code> for a
      /// URL that is not http(s), has no host, carries user information (use a custom header for
      /// credentials) or exceeds 2048 characters; for a reserved or malformed header name, a header
      /// value with a line break, too many or too long headers; or for a timeout outside
      /// 1 s to 30 s.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.Webhook> CreateWebhookAsync(global::Ondewo.Vtsi.CreateWebhookRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CreateWebhookAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Creates a webhook: an HTTP(S) endpoint that receives one request per event, with a JSON
      /// body holding the &lt;code>VtsiEventMessage&lt;/code> (proto3 JSON, original field names).&lt;/p>
      /// &lt;p>Errors: &lt;code>NOT_FOUND&lt;/code> for an unknown project; &lt;code>INVALID_ARGUMENT&lt;/code> for a
      /// URL that is not http(s), has no host, carries user information (use a custom header for
      /// credentials) or exceeds 2048 characters; for a reserved or malformed header name, a header
      /// value with a line break, too many or too long headers; or for a timeout outside
      /// 1 s to 30 s.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.Webhook> CreateWebhookAsync(global::Ondewo.Vtsi.CreateWebhookRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CreateWebhook, null, options, request);
      }
      /// <summary>
      /// &lt;p>Returns a webhook. Custom header values are masked.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.Webhook GetWebhook(global::Ondewo.Vtsi.GetWebhookRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetWebhook(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Returns a webhook. Custom header values are masked.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.Webhook GetWebhook(global::Ondewo.Vtsi.GetWebhookRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetWebhook, null, options, request);
      }
      /// <summary>
      /// &lt;p>Returns a webhook. Custom header values are masked.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.Webhook> GetWebhookAsync(global::Ondewo.Vtsi.GetWebhookRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetWebhookAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Returns a webhook. Custom header values are masked.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.Webhook> GetWebhookAsync(global::Ondewo.Vtsi.GetWebhookRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetWebhook, null, options, request);
      }
      /// <summary>
      /// &lt;p>Updates the fields named in &lt;code>update_mask&lt;/code>: &lt;code>display_name&lt;/code>,
      /// &lt;code>url&lt;/code>, &lt;code>http_method&lt;/code>, &lt;code>custom_headers&lt;/code>, &lt;code>disabled&lt;/code>,
      /// &lt;code>timeout&lt;/code>. &lt;code>custom_headers&lt;/code> replaces the whole map; a value equal to the
      /// mask &lt;code>********&lt;/code> keeps the stored value of that header, so a Get-modify-Update
      /// round trip does not overwrite secrets with the mask.&lt;/p>
      /// &lt;p>Moving the webhook to another origin (scheme, host or port of &lt;code>url&lt;/code>) while custom
      /// headers are stored requires re-sending &lt;code>custom_headers&lt;/code> in the same request, with
      /// their REAL values (or an empty map to drop them): the stored values are never carried to a new
      /// origin, and an update that leaves &lt;code>custom_headers&lt;/code> out of the mask or sends the mask
      /// value &lt;code>********&lt;/code> for any header is rejected with &lt;code>INVALID_ARGUMENT&lt;/code> naming
      /// the headers. A new path on the same origin keeps the stored values.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.Webhook UpdateWebhook(global::Ondewo.Vtsi.UpdateWebhookRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateWebhook(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Updates the fields named in &lt;code>update_mask&lt;/code>: &lt;code>display_name&lt;/code>,
      /// &lt;code>url&lt;/code>, &lt;code>http_method&lt;/code>, &lt;code>custom_headers&lt;/code>, &lt;code>disabled&lt;/code>,
      /// &lt;code>timeout&lt;/code>. &lt;code>custom_headers&lt;/code> replaces the whole map; a value equal to the
      /// mask &lt;code>********&lt;/code> keeps the stored value of that header, so a Get-modify-Update
      /// round trip does not overwrite secrets with the mask.&lt;/p>
      /// &lt;p>Moving the webhook to another origin (scheme, host or port of &lt;code>url&lt;/code>) while custom
      /// headers are stored requires re-sending &lt;code>custom_headers&lt;/code> in the same request, with
      /// their REAL values (or an empty map to drop them): the stored values are never carried to a new
      /// origin, and an update that leaves &lt;code>custom_headers&lt;/code> out of the mask or sends the mask
      /// value &lt;code>********&lt;/code> for any header is rejected with &lt;code>INVALID_ARGUMENT&lt;/code> naming
      /// the headers. A new path on the same origin keeps the stored values.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.Webhook UpdateWebhook(global::Ondewo.Vtsi.UpdateWebhookRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_UpdateWebhook, null, options, request);
      }
      /// <summary>
      /// &lt;p>Updates the fields named in &lt;code>update_mask&lt;/code>: &lt;code>display_name&lt;/code>,
      /// &lt;code>url&lt;/code>, &lt;code>http_method&lt;/code>, &lt;code>custom_headers&lt;/code>, &lt;code>disabled&lt;/code>,
      /// &lt;code>timeout&lt;/code>. &lt;code>custom_headers&lt;/code> replaces the whole map; a value equal to the
      /// mask &lt;code>********&lt;/code> keeps the stored value of that header, so a Get-modify-Update
      /// round trip does not overwrite secrets with the mask.&lt;/p>
      /// &lt;p>Moving the webhook to another origin (scheme, host or port of &lt;code>url&lt;/code>) while custom
      /// headers are stored requires re-sending &lt;code>custom_headers&lt;/code> in the same request, with
      /// their REAL values (or an empty map to drop them): the stored values are never carried to a new
      /// origin, and an update that leaves &lt;code>custom_headers&lt;/code> out of the mask or sends the mask
      /// value &lt;code>********&lt;/code> for any header is rejected with &lt;code>INVALID_ARGUMENT&lt;/code> naming
      /// the headers. A new path on the same origin keeps the stored values.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.Webhook> UpdateWebhookAsync(global::Ondewo.Vtsi.UpdateWebhookRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return UpdateWebhookAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Updates the fields named in &lt;code>update_mask&lt;/code>: &lt;code>display_name&lt;/code>,
      /// &lt;code>url&lt;/code>, &lt;code>http_method&lt;/code>, &lt;code>custom_headers&lt;/code>, &lt;code>disabled&lt;/code>,
      /// &lt;code>timeout&lt;/code>. &lt;code>custom_headers&lt;/code> replaces the whole map; a value equal to the
      /// mask &lt;code>********&lt;/code> keeps the stored value of that header, so a Get-modify-Update
      /// round trip does not overwrite secrets with the mask.&lt;/p>
      /// &lt;p>Moving the webhook to another origin (scheme, host or port of &lt;code>url&lt;/code>) while custom
      /// headers are stored requires re-sending &lt;code>custom_headers&lt;/code> in the same request, with
      /// their REAL values (or an empty map to drop them): the stored values are never carried to a new
      /// origin, and an update that leaves &lt;code>custom_headers&lt;/code> out of the mask or sends the mask
      /// value &lt;code>********&lt;/code> for any header is rejected with &lt;code>INVALID_ARGUMENT&lt;/code> naming
      /// the headers. A new path on the same origin keeps the stored values.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.Webhook> UpdateWebhookAsync(global::Ondewo.Vtsi.UpdateWebhookRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_UpdateWebhook, null, options, request);
      }
      /// <summary>
      /// &lt;p>Deletes a webhook and removes it from every event subscription.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.DeleteWebhookResponse DeleteWebhook(global::Ondewo.Vtsi.DeleteWebhookRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteWebhook(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Deletes a webhook and removes it from every event subscription.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.DeleteWebhookResponse DeleteWebhook(global::Ondewo.Vtsi.DeleteWebhookRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteWebhook, null, options, request);
      }
      /// <summary>
      /// &lt;p>Deletes a webhook and removes it from every event subscription.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.DeleteWebhookResponse> DeleteWebhookAsync(global::Ondewo.Vtsi.DeleteWebhookRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteWebhookAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Deletes a webhook and removes it from every event subscription.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.DeleteWebhookResponse> DeleteWebhookAsync(global::Ondewo.Vtsi.DeleteWebhookRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteWebhook, null, options, request);
      }
      /// <summary>
      /// &lt;p>Lists the webhooks of a project, paged. Custom header values are masked.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.ListWebhooksResponse ListWebhooks(global::Ondewo.Vtsi.ListWebhooksRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListWebhooks(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Lists the webhooks of a project, paged. Custom header values are masked.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.ListWebhooksResponse ListWebhooks(global::Ondewo.Vtsi.ListWebhooksRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListWebhooks, null, options, request);
      }
      /// <summary>
      /// &lt;p>Lists the webhooks of a project, paged. Custom header values are masked.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.ListWebhooksResponse> ListWebhooksAsync(global::Ondewo.Vtsi.ListWebhooksRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListWebhooksAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Lists the webhooks of a project, paged. Custom header values are masked.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.ListWebhooksResponse> ListWebhooksAsync(global::Ondewo.Vtsi.ListWebhooksRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListWebhooks, null, options, request);
      }
      /// <summary>
      /// &lt;p>Sends one &lt;code>VTSI_EVENT_WEBHOOK_TEST&lt;/code> event to a webhook now, without retries,
      /// and reports the outcome. Works on a disabled webhook too, and ignores an open circuit.&lt;/p>
      /// &lt;p>Errors: &lt;code>NOT_FOUND&lt;/code>. A failed delivery is reported in the response, not as an
      /// error status.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.TestWebhookResponse TestWebhook(global::Ondewo.Vtsi.TestWebhookRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TestWebhook(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Sends one &lt;code>VTSI_EVENT_WEBHOOK_TEST&lt;/code> event to a webhook now, without retries,
      /// and reports the outcome. Works on a disabled webhook too, and ignores an open circuit.&lt;/p>
      /// &lt;p>Errors: &lt;code>NOT_FOUND&lt;/code>. A failed delivery is reported in the response, not as an
      /// error status.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.TestWebhookResponse TestWebhook(global::Ondewo.Vtsi.TestWebhookRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_TestWebhook, null, options, request);
      }
      /// <summary>
      /// &lt;p>Sends one &lt;code>VTSI_EVENT_WEBHOOK_TEST&lt;/code> event to a webhook now, without retries,
      /// and reports the outcome. Works on a disabled webhook too, and ignores an open circuit.&lt;/p>
      /// &lt;p>Errors: &lt;code>NOT_FOUND&lt;/code>. A failed delivery is reported in the response, not as an
      /// error status.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.TestWebhookResponse> TestWebhookAsync(global::Ondewo.Vtsi.TestWebhookRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return TestWebhookAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Sends one &lt;code>VTSI_EVENT_WEBHOOK_TEST&lt;/code> event to a webhook now, without retries,
      /// and reports the outcome. Works on a disabled webhook too, and ignores an open circuit.&lt;/p>
      /// &lt;p>Errors: &lt;code>NOT_FOUND&lt;/code>. A failed delivery is reported in the response, not as an
      /// error status.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.TestWebhookResponse> TestWebhookAsync(global::Ondewo.Vtsi.TestWebhookRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_TestWebhook, null, options, request);
      }
      /// <summary>
      /// &lt;p>Streams the events of a project as they happen, selected either by a named event
      /// subscription or by an inline filter. An empty message is sent as a keep-alive. After a
      /// disconnect, pass the last &lt;code>resume_token&lt;/code> to continue where the stream stopped;
      /// events older than the server&amp;apos;s retention (24 h by default) are no longer available, and
      /// the journal records a project&amp;apos;s events only while it has an open stream (and for 1 h
      /// after the last one closed) or an enabled event subscription. A stream sees events of other
      /// server replicas from at most a few seconds after it opened. A client that stops reading for
      /// longer than the server&amp;apos;s stall timeout (30 s by default) is disconnected; reconnect with
      /// the &lt;code>resume_token&lt;/code>. When the project is deleted, the stream delivers
      /// &lt;code>VTSI_EVENT_VTSI_PROJECT_DELETED&lt;/code> and ends.&lt;/p>
      /// &lt;p>Errors: &lt;code>NOT_FOUND&lt;/code> for an unknown project or subscription;
      /// &lt;code>INVALID_ARGUMENT&lt;/code> for a malformed &lt;code>resume_token&lt;/code>;
      /// &lt;code>FAILED_PRECONDITION&lt;/code> for a disabled subscription; &lt;code>RESOURCE_EXHAUSTED&lt;/code>
      /// when the server has no free stream slot.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Ondewo.Vtsi.SubscribeVtsiEventsResponse> SubscribeVtsiEvents(global::Ondewo.Vtsi.SubscribeVtsiEventsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return SubscribeVtsiEvents(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Streams the events of a project as they happen, selected either by a named event
      /// subscription or by an inline filter. An empty message is sent as a keep-alive. After a
      /// disconnect, pass the last &lt;code>resume_token&lt;/code> to continue where the stream stopped;
      /// events older than the server&amp;apos;s retention (24 h by default) are no longer available, and
      /// the journal records a project&amp;apos;s events only while it has an open stream (and for 1 h
      /// after the last one closed) or an enabled event subscription. A stream sees events of other
      /// server replicas from at most a few seconds after it opened. A client that stops reading for
      /// longer than the server&amp;apos;s stall timeout (30 s by default) is disconnected; reconnect with
      /// the &lt;code>resume_token&lt;/code>. When the project is deleted, the stream delivers
      /// &lt;code>VTSI_EVENT_VTSI_PROJECT_DELETED&lt;/code> and ends.&lt;/p>
      /// &lt;p>Errors: &lt;code>NOT_FOUND&lt;/code> for an unknown project or subscription;
      /// &lt;code>INVALID_ARGUMENT&lt;/code> for a malformed &lt;code>resume_token&lt;/code>;
      /// &lt;code>FAILED_PRECONDITION&lt;/code> for a disabled subscription; &lt;code>RESOURCE_EXHAUSTED&lt;/code>
      /// when the server has no free stream slot.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Ondewo.Vtsi.SubscribeVtsiEventsResponse> SubscribeVtsiEvents(global::Ondewo.Vtsi.SubscribeVtsiEventsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_SubscribeVtsiEvents, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override EventsClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new EventsClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(EventsBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_CreateVtsiEventSubscription, serviceImpl.CreateVtsiEventSubscription)
          .AddMethod(__Method_GetVtsiEventSubscription, serviceImpl.GetVtsiEventSubscription)
          .AddMethod(__Method_UpdateVtsiEventSubscription, serviceImpl.UpdateVtsiEventSubscription)
          .AddMethod(__Method_DeleteVtsiEventSubscription, serviceImpl.DeleteVtsiEventSubscription)
          .AddMethod(__Method_ListVtsiEventSubscriptions, serviceImpl.ListVtsiEventSubscriptions)
          .AddMethod(__Method_CreateWebhook, serviceImpl.CreateWebhook)
          .AddMethod(__Method_GetWebhook, serviceImpl.GetWebhook)
          .AddMethod(__Method_UpdateWebhook, serviceImpl.UpdateWebhook)
          .AddMethod(__Method_DeleteWebhook, serviceImpl.DeleteWebhook)
          .AddMethod(__Method_ListWebhooks, serviceImpl.ListWebhooks)
          .AddMethod(__Method_TestWebhook, serviceImpl.TestWebhook)
          .AddMethod(__Method_SubscribeVtsiEvents, serviceImpl.SubscribeVtsiEvents).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, EventsBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_CreateVtsiEventSubscription, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Vtsi.CreateVtsiEventSubscriptionRequest, global::Ondewo.Vtsi.VtsiEventSubscription>(serviceImpl.CreateVtsiEventSubscription));
      serviceBinder.AddMethod(__Method_GetVtsiEventSubscription, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Vtsi.GetVtsiEventSubscriptionRequest, global::Ondewo.Vtsi.VtsiEventSubscription>(serviceImpl.GetVtsiEventSubscription));
      serviceBinder.AddMethod(__Method_UpdateVtsiEventSubscription, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Vtsi.UpdateVtsiEventSubscriptionRequest, global::Ondewo.Vtsi.VtsiEventSubscription>(serviceImpl.UpdateVtsiEventSubscription));
      serviceBinder.AddMethod(__Method_DeleteVtsiEventSubscription, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Vtsi.DeleteVtsiEventSubscriptionRequest, global::Ondewo.Vtsi.DeleteVtsiEventSubscriptionResponse>(serviceImpl.DeleteVtsiEventSubscription));
      serviceBinder.AddMethod(__Method_ListVtsiEventSubscriptions, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Vtsi.ListVtsiEventSubscriptionsRequest, global::Ondewo.Vtsi.ListVtsiEventSubscriptionsResponse>(serviceImpl.ListVtsiEventSubscriptions));
      serviceBinder.AddMethod(__Method_CreateWebhook, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Vtsi.CreateWebhookRequest, global::Ondewo.Vtsi.Webhook>(serviceImpl.CreateWebhook));
      serviceBinder.AddMethod(__Method_GetWebhook, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Vtsi.GetWebhookRequest, global::Ondewo.Vtsi.Webhook>(serviceImpl.GetWebhook));
      serviceBinder.AddMethod(__Method_UpdateWebhook, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Vtsi.UpdateWebhookRequest, global::Ondewo.Vtsi.Webhook>(serviceImpl.UpdateWebhook));
      serviceBinder.AddMethod(__Method_DeleteWebhook, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Vtsi.DeleteWebhookRequest, global::Ondewo.Vtsi.DeleteWebhookResponse>(serviceImpl.DeleteWebhook));
      serviceBinder.AddMethod(__Method_ListWebhooks, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Vtsi.ListWebhooksRequest, global::Ondewo.Vtsi.ListWebhooksResponse>(serviceImpl.ListWebhooks));
      serviceBinder.AddMethod(__Method_TestWebhook, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Vtsi.TestWebhookRequest, global::Ondewo.Vtsi.TestWebhookResponse>(serviceImpl.TestWebhook));
      serviceBinder.AddMethod(__Method_SubscribeVtsiEvents, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Ondewo.Vtsi.SubscribeVtsiEventsRequest, global::Ondewo.Vtsi.SubscribeVtsiEventsResponse>(serviceImpl.SubscribeVtsiEvents));
    }

  }
}
#endregion
