// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ondewo/vtsi/logs.proto
// </auto-generated>
// Original file comments:
// Copyright 2021 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Ondewo.Vtsi {
  /// <summary>
  /// &lt;p>ONDEWO VTSI API&lt;/p>
  /// </summary>
  public static partial class Logs
  {
    static readonly string __ServiceName = "ondewo.vtsi.Logs";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.StreamCallLogsRequest> __Marshaller_ondewo_vtsi_StreamCallLogsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.StreamCallLogsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.StreamCallLogsResponse> __Marshaller_ondewo_vtsi_StreamCallLogsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.StreamCallLogsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.ListCallLogsRequest> __Marshaller_ondewo_vtsi_ListCallLogsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.ListCallLogsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.ListCallLogsResponse> __Marshaller_ondewo_vtsi_ListCallLogsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.ListCallLogsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.GetCallLogStreamRequest> __Marshaller_ondewo_vtsi_GetCallLogStreamRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.GetCallLogStreamRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.CallLogStream> __Marshaller_ondewo_vtsi_CallLogStream = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.CallLogStream.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.ListCallLogStreamsRequest> __Marshaller_ondewo_vtsi_ListCallLogStreamsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.ListCallLogStreamsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.ListCallLogStreamsResponse> __Marshaller_ondewo_vtsi_ListCallLogStreamsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.ListCallLogStreamsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.DeleteCallLogsRequest> __Marshaller_ondewo_vtsi_DeleteCallLogsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.DeleteCallLogsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Vtsi.DeleteCallLogsResponse> __Marshaller_ondewo_vtsi_DeleteCallLogsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Vtsi.DeleteCallLogsResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Vtsi.StreamCallLogsRequest, global::Ondewo.Vtsi.StreamCallLogsResponse> __Method_StreamCallLogs = new grpc::Method<global::Ondewo.Vtsi.StreamCallLogsRequest, global::Ondewo.Vtsi.StreamCallLogsResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "StreamCallLogs",
        __Marshaller_ondewo_vtsi_StreamCallLogsRequest,
        __Marshaller_ondewo_vtsi_StreamCallLogsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Vtsi.ListCallLogsRequest, global::Ondewo.Vtsi.ListCallLogsResponse> __Method_ListCallLogs = new grpc::Method<global::Ondewo.Vtsi.ListCallLogsRequest, global::Ondewo.Vtsi.ListCallLogsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListCallLogs",
        __Marshaller_ondewo_vtsi_ListCallLogsRequest,
        __Marshaller_ondewo_vtsi_ListCallLogsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Vtsi.GetCallLogStreamRequest, global::Ondewo.Vtsi.CallLogStream> __Method_GetCallLogStream = new grpc::Method<global::Ondewo.Vtsi.GetCallLogStreamRequest, global::Ondewo.Vtsi.CallLogStream>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetCallLogStream",
        __Marshaller_ondewo_vtsi_GetCallLogStreamRequest,
        __Marshaller_ondewo_vtsi_CallLogStream);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Vtsi.ListCallLogStreamsRequest, global::Ondewo.Vtsi.ListCallLogStreamsResponse> __Method_ListCallLogStreams = new grpc::Method<global::Ondewo.Vtsi.ListCallLogStreamsRequest, global::Ondewo.Vtsi.ListCallLogStreamsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListCallLogStreams",
        __Marshaller_ondewo_vtsi_ListCallLogStreamsRequest,
        __Marshaller_ondewo_vtsi_ListCallLogStreamsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Vtsi.DeleteCallLogsRequest, global::Ondewo.Vtsi.DeleteCallLogsResponse> __Method_DeleteCallLogs = new grpc::Method<global::Ondewo.Vtsi.DeleteCallLogsRequest, global::Ondewo.Vtsi.DeleteCallLogsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteCallLogs",
        __Marshaller_ondewo_vtsi_DeleteCallLogsRequest,
        __Marshaller_ondewo_vtsi_DeleteCallLogsResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Ondewo.Vtsi.LogsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Logs</summary>
    [grpc::BindServiceMethod(typeof(Logs), "BindService")]
    public abstract partial class LogsBase
    {
      /// <summary>
      /// &lt;p>Streams the container logs of the ondewo-sip / ondewo-csi containers of a VTSI project as
      /// they are captured, in the manner of &lt;code>docker logs --follow&lt;/code>. The stream replays
      /// &lt;code>tail_lines&lt;/code> historical entries and then follows. It stays open until the capture
      /// of every matching log stream has terminated, until the client disconnects, or until the
      /// server-side maximum stream duration is reached.&lt;/p>
      /// &lt;p>Entries are served from the VTSI database rather than from the docker daemon, so a
      /// container that has already been removed still streams. Secrets are redacted server-side.&lt;/p>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task StreamCallLogs(global::Ondewo.Vtsi.StreamCallLogsRequest request, grpc::IServerStreamWriter<global::Ondewo.Vtsi.StreamCallLogsResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>Returns a bounded, filtered page of captured container log entries. Supports a time window,
      /// severity filtering, a regular expression, a plain-text search and cursor paging in both
      /// directions for infinite scrolling. Secrets are redacted server-side.&lt;/p>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Vtsi.ListCallLogsResponse> ListCallLogs(global::Ondewo.Vtsi.ListCallLogsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>Returns the capture state of a single log stream, i.e. of one capture generation of one
      /// container.&lt;/p>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Vtsi.CallLogStream> GetCallLogStream(global::Ondewo.Vtsi.GetCallLogStreamRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>Lists the log streams VTSI has captured for a project. A single container yields a new log
      /// stream every time it is recreated, because a recreated container is a new docker container
      /// whose previous logs no longer exist.&lt;/p>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Vtsi.ListCallLogStreamsResponse> ListCallLogStreams(global::Ondewo.Vtsi.ListCallLogStreamsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// &lt;p>Permanently deletes captured log entries matching a filter. This is the erasure path for
      /// data-subject requests: retention answers &amp;quot;delete everything older than N days&amp;quot;, this
      /// answers &amp;quot;delete everything for this call or this phone number&amp;quot;.&lt;/p>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Vtsi.DeleteCallLogsResponse> DeleteCallLogs(global::Ondewo.Vtsi.DeleteCallLogsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Logs</summary>
    public partial class LogsClient : grpc::ClientBase<LogsClient>
    {
      /// <summary>Creates a new client for Logs</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public LogsClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Logs that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public LogsClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected LogsClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected LogsClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// &lt;p>Streams the container logs of the ondewo-sip / ondewo-csi containers of a VTSI project as
      /// they are captured, in the manner of &lt;code>docker logs --follow&lt;/code>. The stream replays
      /// &lt;code>tail_lines&lt;/code> historical entries and then follows. It stays open until the capture
      /// of every matching log stream has terminated, until the client disconnects, or until the
      /// server-side maximum stream duration is reached.&lt;/p>
      /// &lt;p>Entries are served from the VTSI database rather than from the docker daemon, so a
      /// container that has already been removed still streams. Secrets are redacted server-side.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Ondewo.Vtsi.StreamCallLogsResponse> StreamCallLogs(global::Ondewo.Vtsi.StreamCallLogsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StreamCallLogs(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Streams the container logs of the ondewo-sip / ondewo-csi containers of a VTSI project as
      /// they are captured, in the manner of &lt;code>docker logs --follow&lt;/code>. The stream replays
      /// &lt;code>tail_lines&lt;/code> historical entries and then follows. It stays open until the capture
      /// of every matching log stream has terminated, until the client disconnects, or until the
      /// server-side maximum stream duration is reached.&lt;/p>
      /// &lt;p>Entries are served from the VTSI database rather than from the docker daemon, so a
      /// container that has already been removed still streams. Secrets are redacted server-side.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Ondewo.Vtsi.StreamCallLogsResponse> StreamCallLogs(global::Ondewo.Vtsi.StreamCallLogsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_StreamCallLogs, null, options, request);
      }
      /// <summary>
      /// &lt;p>Returns a bounded, filtered page of captured container log entries. Supports a time window,
      /// severity filtering, a regular expression, a plain-text search and cursor paging in both
      /// directions for infinite scrolling. Secrets are redacted server-side.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.ListCallLogsResponse ListCallLogs(global::Ondewo.Vtsi.ListCallLogsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListCallLogs(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Returns a bounded, filtered page of captured container log entries. Supports a time window,
      /// severity filtering, a regular expression, a plain-text search and cursor paging in both
      /// directions for infinite scrolling. Secrets are redacted server-side.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.ListCallLogsResponse ListCallLogs(global::Ondewo.Vtsi.ListCallLogsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListCallLogs, null, options, request);
      }
      /// <summary>
      /// &lt;p>Returns a bounded, filtered page of captured container log entries. Supports a time window,
      /// severity filtering, a regular expression, a plain-text search and cursor paging in both
      /// directions for infinite scrolling. Secrets are redacted server-side.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.ListCallLogsResponse> ListCallLogsAsync(global::Ondewo.Vtsi.ListCallLogsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListCallLogsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Returns a bounded, filtered page of captured container log entries. Supports a time window,
      /// severity filtering, a regular expression, a plain-text search and cursor paging in both
      /// directions for infinite scrolling. Secrets are redacted server-side.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.ListCallLogsResponse> ListCallLogsAsync(global::Ondewo.Vtsi.ListCallLogsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListCallLogs, null, options, request);
      }
      /// <summary>
      /// &lt;p>Returns the capture state of a single log stream, i.e. of one capture generation of one
      /// container.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.CallLogStream GetCallLogStream(global::Ondewo.Vtsi.GetCallLogStreamRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCallLogStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Returns the capture state of a single log stream, i.e. of one capture generation of one
      /// container.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.CallLogStream GetCallLogStream(global::Ondewo.Vtsi.GetCallLogStreamRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetCallLogStream, null, options, request);
      }
      /// <summary>
      /// &lt;p>Returns the capture state of a single log stream, i.e. of one capture generation of one
      /// container.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.CallLogStream> GetCallLogStreamAsync(global::Ondewo.Vtsi.GetCallLogStreamRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetCallLogStreamAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Returns the capture state of a single log stream, i.e. of one capture generation of one
      /// container.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.CallLogStream> GetCallLogStreamAsync(global::Ondewo.Vtsi.GetCallLogStreamRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetCallLogStream, null, options, request);
      }
      /// <summary>
      /// &lt;p>Lists the log streams VTSI has captured for a project. A single container yields a new log
      /// stream every time it is recreated, because a recreated container is a new docker container
      /// whose previous logs no longer exist.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.ListCallLogStreamsResponse ListCallLogStreams(global::Ondewo.Vtsi.ListCallLogStreamsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListCallLogStreams(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Lists the log streams VTSI has captured for a project. A single container yields a new log
      /// stream every time it is recreated, because a recreated container is a new docker container
      /// whose previous logs no longer exist.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.ListCallLogStreamsResponse ListCallLogStreams(global::Ondewo.Vtsi.ListCallLogStreamsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListCallLogStreams, null, options, request);
      }
      /// <summary>
      /// &lt;p>Lists the log streams VTSI has captured for a project. A single container yields a new log
      /// stream every time it is recreated, because a recreated container is a new docker container
      /// whose previous logs no longer exist.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.ListCallLogStreamsResponse> ListCallLogStreamsAsync(global::Ondewo.Vtsi.ListCallLogStreamsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListCallLogStreamsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Lists the log streams VTSI has captured for a project. A single container yields a new log
      /// stream every time it is recreated, because a recreated container is a new docker container
      /// whose previous logs no longer exist.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.ListCallLogStreamsResponse> ListCallLogStreamsAsync(global::Ondewo.Vtsi.ListCallLogStreamsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListCallLogStreams, null, options, request);
      }
      /// <summary>
      /// &lt;p>Permanently deletes captured log entries matching a filter. This is the erasure path for
      /// data-subject requests: retention answers &amp;quot;delete everything older than N days&amp;quot;, this
      /// answers &amp;quot;delete everything for this call or this phone number&amp;quot;.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.DeleteCallLogsResponse DeleteCallLogs(global::Ondewo.Vtsi.DeleteCallLogsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteCallLogs(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Permanently deletes captured log entries matching a filter. This is the erasure path for
      /// data-subject requests: retention answers &amp;quot;delete everything older than N days&amp;quot;, this
      /// answers &amp;quot;delete everything for this call or this phone number&amp;quot;.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Vtsi.DeleteCallLogsResponse DeleteCallLogs(global::Ondewo.Vtsi.DeleteCallLogsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteCallLogs, null, options, request);
      }
      /// <summary>
      /// &lt;p>Permanently deletes captured log entries matching a filter. This is the erasure path for
      /// data-subject requests: retention answers &amp;quot;delete everything older than N days&amp;quot;, this
      /// answers &amp;quot;delete everything for this call or this phone number&amp;quot;.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.DeleteCallLogsResponse> DeleteCallLogsAsync(global::Ondewo.Vtsi.DeleteCallLogsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteCallLogsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// &lt;p>Permanently deletes captured log entries matching a filter. This is the erasure path for
      /// data-subject requests: retention answers &amp;quot;delete everything older than N days&amp;quot;, this
      /// answers &amp;quot;delete everything for this call or this phone number&amp;quot;.&lt;/p>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Vtsi.DeleteCallLogsResponse> DeleteCallLogsAsync(global::Ondewo.Vtsi.DeleteCallLogsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteCallLogs, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override LogsClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new LogsClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(LogsBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_StreamCallLogs, serviceImpl.StreamCallLogs)
          .AddMethod(__Method_ListCallLogs, serviceImpl.ListCallLogs)
          .AddMethod(__Method_GetCallLogStream, serviceImpl.GetCallLogStream)
          .AddMethod(__Method_ListCallLogStreams, serviceImpl.ListCallLogStreams)
          .AddMethod(__Method_DeleteCallLogs, serviceImpl.DeleteCallLogs).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, LogsBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_StreamCallLogs, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Ondewo.Vtsi.StreamCallLogsRequest, global::Ondewo.Vtsi.StreamCallLogsResponse>(serviceImpl.StreamCallLogs));
      serviceBinder.AddMethod(__Method_ListCallLogs, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Vtsi.ListCallLogsRequest, global::Ondewo.Vtsi.ListCallLogsResponse>(serviceImpl.ListCallLogs));
      serviceBinder.AddMethod(__Method_GetCallLogStream, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Vtsi.GetCallLogStreamRequest, global::Ondewo.Vtsi.CallLogStream>(serviceImpl.GetCallLogStream));
      serviceBinder.AddMethod(__Method_ListCallLogStreams, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Vtsi.ListCallLogStreamsRequest, global::Ondewo.Vtsi.ListCallLogStreamsResponse>(serviceImpl.ListCallLogStreams));
      serviceBinder.AddMethod(__Method_DeleteCallLogs, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Vtsi.DeleteCallLogsRequest, global::Ondewo.Vtsi.DeleteCallLogsResponse>(serviceImpl.DeleteCallLogs));
    }

  }
}
#endregion
