// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ondewo/nlu/aiservices.proto
// </auto-generated>
// Original file comments:
// Copyright 2020-2026 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Ondewo.Nlu {
  /// <summary>
  /// The Central class defining the ondewo ai services
  /// </summary>
  public static partial class AiServices
  {
    static readonly string __ServiceName = "ondewo.nlu.AiServices";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.ExtractEntitiesRequest> __Marshaller_ondewo_nlu_ExtractEntitiesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.ExtractEntitiesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.ExtractEntitiesResponse> __Marshaller_ondewo_nlu_ExtractEntitiesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.ExtractEntitiesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.GenerateUserSaysRequest> __Marshaller_ondewo_nlu_GenerateUserSaysRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.GenerateUserSaysRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.GenerateUserSaysResponse> __Marshaller_ondewo_nlu_GenerateUserSaysResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.GenerateUserSaysResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.GenerateResponsesRequest> __Marshaller_ondewo_nlu_GenerateResponsesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.GenerateResponsesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.GenerateResponsesResponse> __Marshaller_ondewo_nlu_GenerateResponsesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.GenerateResponsesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.GetAlternativeSentencesRequest> __Marshaller_ondewo_nlu_GetAlternativeSentencesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.GetAlternativeSentencesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.GetAlternativeSentencesResponse> __Marshaller_ondewo_nlu_GetAlternativeSentencesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.GetAlternativeSentencesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.GetAlternativeTrainingPhrasesRequest> __Marshaller_ondewo_nlu_GetAlternativeTrainingPhrasesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.GetAlternativeTrainingPhrasesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.GetAlternativeTrainingPhrasesResponse> __Marshaller_ondewo_nlu_GetAlternativeTrainingPhrasesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.GetAlternativeTrainingPhrasesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.GetSynonymsRequest> __Marshaller_ondewo_nlu_GetSynonymsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.GetSynonymsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.GetSynonymsResponse> __Marshaller_ondewo_nlu_GetSynonymsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.GetSynonymsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.ClassifyIntentsRequest> __Marshaller_ondewo_nlu_ClassifyIntentsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.ClassifyIntentsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.ClassifyIntentsResponse> __Marshaller_ondewo_nlu_ClassifyIntentsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.ClassifyIntentsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.ExtractEntitiesFuzzyRequest> __Marshaller_ondewo_nlu_ExtractEntitiesFuzzyRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.ExtractEntitiesFuzzyRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.LlmGenerateRequest> __Marshaller_ondewo_nlu_LlmGenerateRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.LlmGenerateRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.LlmGenerateResponse> __Marshaller_ondewo_nlu_LlmGenerateResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.LlmGenerateResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.StreamingLlmGenerateResponse> __Marshaller_ondewo_nlu_StreamingLlmGenerateResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.StreamingLlmGenerateResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.ListLlmModelsRequest> __Marshaller_ondewo_nlu_ListLlmModelsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.ListLlmModelsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.ListLlmModelsResponse> __Marshaller_ondewo_nlu_ListLlmModelsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.ListLlmModelsResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.ExtractEntitiesRequest, global::Ondewo.Nlu.ExtractEntitiesResponse> __Method_ExtractEntities = new grpc::Method<global::Ondewo.Nlu.ExtractEntitiesRequest, global::Ondewo.Nlu.ExtractEntitiesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ExtractEntities",
        __Marshaller_ondewo_nlu_ExtractEntitiesRequest,
        __Marshaller_ondewo_nlu_ExtractEntitiesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.GenerateUserSaysRequest, global::Ondewo.Nlu.GenerateUserSaysResponse> __Method_GenerateUserSays = new grpc::Method<global::Ondewo.Nlu.GenerateUserSaysRequest, global::Ondewo.Nlu.GenerateUserSaysResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GenerateUserSays",
        __Marshaller_ondewo_nlu_GenerateUserSaysRequest,
        __Marshaller_ondewo_nlu_GenerateUserSaysResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.GenerateResponsesRequest, global::Ondewo.Nlu.GenerateResponsesResponse> __Method_GenerateResponses = new grpc::Method<global::Ondewo.Nlu.GenerateResponsesRequest, global::Ondewo.Nlu.GenerateResponsesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GenerateResponses",
        __Marshaller_ondewo_nlu_GenerateResponsesRequest,
        __Marshaller_ondewo_nlu_GenerateResponsesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.GetAlternativeSentencesRequest, global::Ondewo.Nlu.GetAlternativeSentencesResponse> __Method_GetAlternativeSentences = new grpc::Method<global::Ondewo.Nlu.GetAlternativeSentencesRequest, global::Ondewo.Nlu.GetAlternativeSentencesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAlternativeSentences",
        __Marshaller_ondewo_nlu_GetAlternativeSentencesRequest,
        __Marshaller_ondewo_nlu_GetAlternativeSentencesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.GetAlternativeTrainingPhrasesRequest, global::Ondewo.Nlu.GetAlternativeTrainingPhrasesResponse> __Method_GetAlternativeTrainingPhrases = new grpc::Method<global::Ondewo.Nlu.GetAlternativeTrainingPhrasesRequest, global::Ondewo.Nlu.GetAlternativeTrainingPhrasesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetAlternativeTrainingPhrases",
        __Marshaller_ondewo_nlu_GetAlternativeTrainingPhrasesRequest,
        __Marshaller_ondewo_nlu_GetAlternativeTrainingPhrasesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.GetSynonymsRequest, global::Ondewo.Nlu.GetSynonymsResponse> __Method_GetSynonyms = new grpc::Method<global::Ondewo.Nlu.GetSynonymsRequest, global::Ondewo.Nlu.GetSynonymsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetSynonyms",
        __Marshaller_ondewo_nlu_GetSynonymsRequest,
        __Marshaller_ondewo_nlu_GetSynonymsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.ClassifyIntentsRequest, global::Ondewo.Nlu.ClassifyIntentsResponse> __Method_ClassifyIntents = new grpc::Method<global::Ondewo.Nlu.ClassifyIntentsRequest, global::Ondewo.Nlu.ClassifyIntentsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ClassifyIntents",
        __Marshaller_ondewo_nlu_ClassifyIntentsRequest,
        __Marshaller_ondewo_nlu_ClassifyIntentsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.ExtractEntitiesFuzzyRequest, global::Ondewo.Nlu.ExtractEntitiesResponse> __Method_ExtractEntitiesFuzzy = new grpc::Method<global::Ondewo.Nlu.ExtractEntitiesFuzzyRequest, global::Ondewo.Nlu.ExtractEntitiesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ExtractEntitiesFuzzy",
        __Marshaller_ondewo_nlu_ExtractEntitiesFuzzyRequest,
        __Marshaller_ondewo_nlu_ExtractEntitiesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.LlmGenerateRequest, global::Ondewo.Nlu.LlmGenerateResponse> __Method_LlmGenerate = new grpc::Method<global::Ondewo.Nlu.LlmGenerateRequest, global::Ondewo.Nlu.LlmGenerateResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "LlmGenerate",
        __Marshaller_ondewo_nlu_LlmGenerateRequest,
        __Marshaller_ondewo_nlu_LlmGenerateResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.LlmGenerateRequest, global::Ondewo.Nlu.StreamingLlmGenerateResponse> __Method_StreamingLlmGenerate = new grpc::Method<global::Ondewo.Nlu.LlmGenerateRequest, global::Ondewo.Nlu.StreamingLlmGenerateResponse>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "StreamingLlmGenerate",
        __Marshaller_ondewo_nlu_LlmGenerateRequest,
        __Marshaller_ondewo_nlu_StreamingLlmGenerateResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.ListLlmModelsRequest, global::Ondewo.Nlu.ListLlmModelsResponse> __Method_ListLlmModels = new grpc::Method<global::Ondewo.Nlu.ListLlmModelsRequest, global::Ondewo.Nlu.ListLlmModelsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListLlmModels",
        __Marshaller_ondewo_nlu_ListLlmModelsRequest,
        __Marshaller_ondewo_nlu_ListLlmModelsResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Ondewo.Nlu.AiservicesReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of AiServices</summary>
    [grpc::BindServiceMethod(typeof(AiServices), "BindService")]
    public abstract partial class AiServicesBase
    {
      /// <summary>
      /// Processes a natural language query and returns detected entities
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.ExtractEntitiesResponse> ExtractEntities(global::Ondewo.Nlu.ExtractEntitiesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Generates a list of training phrases
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.GenerateUserSaysResponse> GenerateUserSays(global::Ondewo.Nlu.GenerateUserSaysRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Generate responses from all intents using synonyms
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.GenerateResponsesResponse> GenerateResponses(global::Ondewo.Nlu.GenerateResponsesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Generates alternative phrase based on original phrase
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.GetAlternativeSentencesResponse> GetAlternativeSentences(global::Ondewo.Nlu.GetAlternativeSentencesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Generates alternative training phrase based on original training phrase
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.GetAlternativeTrainingPhrasesResponse> GetAlternativeTrainingPhrases(global::Ondewo.Nlu.GetAlternativeTrainingPhrasesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Generates synonyms for a certain word
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.GetSynonymsResponse> GetSynonyms(global::Ondewo.Nlu.GetSynonymsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Preprocess text and detects intents in a sentence
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.ClassifyIntentsResponse> ClassifyIntents(global::Ondewo.Nlu.ClassifyIntentsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Processes a natural language query and returns detected entities
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.ExtractEntitiesResponse> ExtractEntitiesFuzzy(global::Ondewo.Nlu.ExtractEntitiesFuzzyRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Generates a single response from a Large Language Model (LLM).
      /// This RPC method allows a client to make a request to the LLM and receive
      /// a single complete response based on the input parameters provided.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.LlmGenerateResponse> LlmGenerate(global::Ondewo.Nlu.LlmGenerateRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Generates a response from the LLM in a streaming format.
      /// This RPC allows continuous streaming of responses from the model,
      /// which is useful for real-time applications or large outputs.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task StreamingLlmGenerate(global::Ondewo.Nlu.LlmGenerateRequest request, grpc::IServerStreamWriter<global::Ondewo.Nlu.StreamingLlmGenerateResponse> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Lists available Large Language Models (LLMs) for a specified CCAI service.
      /// This RPC method allows clients to retrieve metadata about all LLM models associated
      /// with a particular service within a project, including model names, descriptions, and providers.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.ListLlmModelsResponse> ListLlmModels(global::Ondewo.Nlu.ListLlmModelsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for AiServices</summary>
    public partial class AiServicesClient : grpc::ClientBase<AiServicesClient>
    {
      /// <summary>Creates a new client for AiServices</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public AiServicesClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for AiServices that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public AiServicesClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected AiServicesClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected AiServicesClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Processes a natural language query and returns detected entities
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.ExtractEntitiesResponse ExtractEntities(global::Ondewo.Nlu.ExtractEntitiesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ExtractEntities(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Processes a natural language query and returns detected entities
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.ExtractEntitiesResponse ExtractEntities(global::Ondewo.Nlu.ExtractEntitiesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ExtractEntities, null, options, request);
      }
      /// <summary>
      /// Processes a natural language query and returns detected entities
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.ExtractEntitiesResponse> ExtractEntitiesAsync(global::Ondewo.Nlu.ExtractEntitiesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ExtractEntitiesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Processes a natural language query and returns detected entities
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.ExtractEntitiesResponse> ExtractEntitiesAsync(global::Ondewo.Nlu.ExtractEntitiesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ExtractEntities, null, options, request);
      }
      /// <summary>
      /// Generates a list of training phrases
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.GenerateUserSaysResponse GenerateUserSays(global::Ondewo.Nlu.GenerateUserSaysRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GenerateUserSays(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates a list of training phrases
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.GenerateUserSaysResponse GenerateUserSays(global::Ondewo.Nlu.GenerateUserSaysRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GenerateUserSays, null, options, request);
      }
      /// <summary>
      /// Generates a list of training phrases
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.GenerateUserSaysResponse> GenerateUserSaysAsync(global::Ondewo.Nlu.GenerateUserSaysRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GenerateUserSaysAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates a list of training phrases
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.GenerateUserSaysResponse> GenerateUserSaysAsync(global::Ondewo.Nlu.GenerateUserSaysRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GenerateUserSays, null, options, request);
      }
      /// <summary>
      /// Generate responses from all intents using synonyms
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.GenerateResponsesResponse GenerateResponses(global::Ondewo.Nlu.GenerateResponsesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GenerateResponses(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generate responses from all intents using synonyms
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.GenerateResponsesResponse GenerateResponses(global::Ondewo.Nlu.GenerateResponsesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GenerateResponses, null, options, request);
      }
      /// <summary>
      /// Generate responses from all intents using synonyms
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.GenerateResponsesResponse> GenerateResponsesAsync(global::Ondewo.Nlu.GenerateResponsesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GenerateResponsesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generate responses from all intents using synonyms
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.GenerateResponsesResponse> GenerateResponsesAsync(global::Ondewo.Nlu.GenerateResponsesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GenerateResponses, null, options, request);
      }
      /// <summary>
      /// Generates alternative phrase based on original phrase
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.GetAlternativeSentencesResponse GetAlternativeSentences(global::Ondewo.Nlu.GetAlternativeSentencesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAlternativeSentences(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates alternative phrase based on original phrase
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.GetAlternativeSentencesResponse GetAlternativeSentences(global::Ondewo.Nlu.GetAlternativeSentencesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAlternativeSentences, null, options, request);
      }
      /// <summary>
      /// Generates alternative phrase based on original phrase
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.GetAlternativeSentencesResponse> GetAlternativeSentencesAsync(global::Ondewo.Nlu.GetAlternativeSentencesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAlternativeSentencesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates alternative phrase based on original phrase
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.GetAlternativeSentencesResponse> GetAlternativeSentencesAsync(global::Ondewo.Nlu.GetAlternativeSentencesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAlternativeSentences, null, options, request);
      }
      /// <summary>
      /// Generates alternative training phrase based on original training phrase
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.GetAlternativeTrainingPhrasesResponse GetAlternativeTrainingPhrases(global::Ondewo.Nlu.GetAlternativeTrainingPhrasesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAlternativeTrainingPhrases(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates alternative training phrase based on original training phrase
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.GetAlternativeTrainingPhrasesResponse GetAlternativeTrainingPhrases(global::Ondewo.Nlu.GetAlternativeTrainingPhrasesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetAlternativeTrainingPhrases, null, options, request);
      }
      /// <summary>
      /// Generates alternative training phrase based on original training phrase
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.GetAlternativeTrainingPhrasesResponse> GetAlternativeTrainingPhrasesAsync(global::Ondewo.Nlu.GetAlternativeTrainingPhrasesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetAlternativeTrainingPhrasesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates alternative training phrase based on original training phrase
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.GetAlternativeTrainingPhrasesResponse> GetAlternativeTrainingPhrasesAsync(global::Ondewo.Nlu.GetAlternativeTrainingPhrasesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetAlternativeTrainingPhrases, null, options, request);
      }
      /// <summary>
      /// Generates synonyms for a certain word
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.GetSynonymsResponse GetSynonyms(global::Ondewo.Nlu.GetSynonymsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSynonyms(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates synonyms for a certain word
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.GetSynonymsResponse GetSynonyms(global::Ondewo.Nlu.GetSynonymsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetSynonyms, null, options, request);
      }
      /// <summary>
      /// Generates synonyms for a certain word
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.GetSynonymsResponse> GetSynonymsAsync(global::Ondewo.Nlu.GetSynonymsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetSynonymsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates synonyms for a certain word
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.GetSynonymsResponse> GetSynonymsAsync(global::Ondewo.Nlu.GetSynonymsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetSynonyms, null, options, request);
      }
      /// <summary>
      /// Preprocess text and detects intents in a sentence
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.ClassifyIntentsResponse ClassifyIntents(global::Ondewo.Nlu.ClassifyIntentsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ClassifyIntents(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Preprocess text and detects intents in a sentence
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.ClassifyIntentsResponse ClassifyIntents(global::Ondewo.Nlu.ClassifyIntentsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ClassifyIntents, null, options, request);
      }
      /// <summary>
      /// Preprocess text and detects intents in a sentence
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.ClassifyIntentsResponse> ClassifyIntentsAsync(global::Ondewo.Nlu.ClassifyIntentsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ClassifyIntentsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Preprocess text and detects intents in a sentence
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.ClassifyIntentsResponse> ClassifyIntentsAsync(global::Ondewo.Nlu.ClassifyIntentsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ClassifyIntents, null, options, request);
      }
      /// <summary>
      /// Processes a natural language query and returns detected entities
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.ExtractEntitiesResponse ExtractEntitiesFuzzy(global::Ondewo.Nlu.ExtractEntitiesFuzzyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ExtractEntitiesFuzzy(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Processes a natural language query and returns detected entities
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.ExtractEntitiesResponse ExtractEntitiesFuzzy(global::Ondewo.Nlu.ExtractEntitiesFuzzyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ExtractEntitiesFuzzy, null, options, request);
      }
      /// <summary>
      /// Processes a natural language query and returns detected entities
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.ExtractEntitiesResponse> ExtractEntitiesFuzzyAsync(global::Ondewo.Nlu.ExtractEntitiesFuzzyRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ExtractEntitiesFuzzyAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Processes a natural language query and returns detected entities
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.ExtractEntitiesResponse> ExtractEntitiesFuzzyAsync(global::Ondewo.Nlu.ExtractEntitiesFuzzyRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ExtractEntitiesFuzzy, null, options, request);
      }
      /// <summary>
      /// Generates a single response from a Large Language Model (LLM).
      /// This RPC method allows a client to make a request to the LLM and receive
      /// a single complete response based on the input parameters provided.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.LlmGenerateResponse LlmGenerate(global::Ondewo.Nlu.LlmGenerateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LlmGenerate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates a single response from a Large Language Model (LLM).
      /// This RPC method allows a client to make a request to the LLM and receive
      /// a single complete response based on the input parameters provided.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.LlmGenerateResponse LlmGenerate(global::Ondewo.Nlu.LlmGenerateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_LlmGenerate, null, options, request);
      }
      /// <summary>
      /// Generates a single response from a Large Language Model (LLM).
      /// This RPC method allows a client to make a request to the LLM and receive
      /// a single complete response based on the input parameters provided.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.LlmGenerateResponse> LlmGenerateAsync(global::Ondewo.Nlu.LlmGenerateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return LlmGenerateAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates a single response from a Large Language Model (LLM).
      /// This RPC method allows a client to make a request to the LLM and receive
      /// a single complete response based on the input parameters provided.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.LlmGenerateResponse> LlmGenerateAsync(global::Ondewo.Nlu.LlmGenerateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_LlmGenerate, null, options, request);
      }
      /// <summary>
      /// Generates a response from the LLM in a streaming format.
      /// This RPC allows continuous streaming of responses from the model,
      /// which is useful for real-time applications or large outputs.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Ondewo.Nlu.StreamingLlmGenerateResponse> StreamingLlmGenerate(global::Ondewo.Nlu.LlmGenerateRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StreamingLlmGenerate(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Generates a response from the LLM in a streaming format.
      /// This RPC allows continuous streaming of responses from the model,
      /// which is useful for real-time applications or large outputs.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Ondewo.Nlu.StreamingLlmGenerateResponse> StreamingLlmGenerate(global::Ondewo.Nlu.LlmGenerateRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_StreamingLlmGenerate, null, options, request);
      }
      /// <summary>
      /// Lists available Large Language Models (LLMs) for a specified CCAI service.
      /// This RPC method allows clients to retrieve metadata about all LLM models associated
      /// with a particular service within a project, including model names, descriptions, and providers.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.ListLlmModelsResponse ListLlmModels(global::Ondewo.Nlu.ListLlmModelsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListLlmModels(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Lists available Large Language Models (LLMs) for a specified CCAI service.
      /// This RPC method allows clients to retrieve metadata about all LLM models associated
      /// with a particular service within a project, including model names, descriptions, and providers.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.ListLlmModelsResponse ListLlmModels(global::Ondewo.Nlu.ListLlmModelsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListLlmModels, null, options, request);
      }
      /// <summary>
      /// Lists available Large Language Models (LLMs) for a specified CCAI service.
      /// This RPC method allows clients to retrieve metadata about all LLM models associated
      /// with a particular service within a project, including model names, descriptions, and providers.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.ListLlmModelsResponse> ListLlmModelsAsync(global::Ondewo.Nlu.ListLlmModelsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListLlmModelsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Lists available Large Language Models (LLMs) for a specified CCAI service.
      /// This RPC method allows clients to retrieve metadata about all LLM models associated
      /// with a particular service within a project, including model names, descriptions, and providers.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.ListLlmModelsResponse> ListLlmModelsAsync(global::Ondewo.Nlu.ListLlmModelsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListLlmModels, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override AiServicesClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new AiServicesClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(AiServicesBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ExtractEntities, serviceImpl.ExtractEntities)
          .AddMethod(__Method_GenerateUserSays, serviceImpl.GenerateUserSays)
          .AddMethod(__Method_GenerateResponses, serviceImpl.GenerateResponses)
          .AddMethod(__Method_GetAlternativeSentences, serviceImpl.GetAlternativeSentences)
          .AddMethod(__Method_GetAlternativeTrainingPhrases, serviceImpl.GetAlternativeTrainingPhrases)
          .AddMethod(__Method_GetSynonyms, serviceImpl.GetSynonyms)
          .AddMethod(__Method_ClassifyIntents, serviceImpl.ClassifyIntents)
          .AddMethod(__Method_ExtractEntitiesFuzzy, serviceImpl.ExtractEntitiesFuzzy)
          .AddMethod(__Method_LlmGenerate, serviceImpl.LlmGenerate)
          .AddMethod(__Method_StreamingLlmGenerate, serviceImpl.StreamingLlmGenerate)
          .AddMethod(__Method_ListLlmModels, serviceImpl.ListLlmModels).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, AiServicesBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ExtractEntities, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.ExtractEntitiesRequest, global::Ondewo.Nlu.ExtractEntitiesResponse>(serviceImpl.ExtractEntities));
      serviceBinder.AddMethod(__Method_GenerateUserSays, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.GenerateUserSaysRequest, global::Ondewo.Nlu.GenerateUserSaysResponse>(serviceImpl.GenerateUserSays));
      serviceBinder.AddMethod(__Method_GenerateResponses, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.GenerateResponsesRequest, global::Ondewo.Nlu.GenerateResponsesResponse>(serviceImpl.GenerateResponses));
      serviceBinder.AddMethod(__Method_GetAlternativeSentences, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.GetAlternativeSentencesRequest, global::Ondewo.Nlu.GetAlternativeSentencesResponse>(serviceImpl.GetAlternativeSentences));
      serviceBinder.AddMethod(__Method_GetAlternativeTrainingPhrases, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.GetAlternativeTrainingPhrasesRequest, global::Ondewo.Nlu.GetAlternativeTrainingPhrasesResponse>(serviceImpl.GetAlternativeTrainingPhrases));
      serviceBinder.AddMethod(__Method_GetSynonyms, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.GetSynonymsRequest, global::Ondewo.Nlu.GetSynonymsResponse>(serviceImpl.GetSynonyms));
      serviceBinder.AddMethod(__Method_ClassifyIntents, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.ClassifyIntentsRequest, global::Ondewo.Nlu.ClassifyIntentsResponse>(serviceImpl.ClassifyIntents));
      serviceBinder.AddMethod(__Method_ExtractEntitiesFuzzy, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.ExtractEntitiesFuzzyRequest, global::Ondewo.Nlu.ExtractEntitiesResponse>(serviceImpl.ExtractEntitiesFuzzy));
      serviceBinder.AddMethod(__Method_LlmGenerate, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.LlmGenerateRequest, global::Ondewo.Nlu.LlmGenerateResponse>(serviceImpl.LlmGenerate));
      serviceBinder.AddMethod(__Method_StreamingLlmGenerate, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Ondewo.Nlu.LlmGenerateRequest, global::Ondewo.Nlu.StreamingLlmGenerateResponse>(serviceImpl.StreamingLlmGenerate));
      serviceBinder.AddMethod(__Method_ListLlmModels, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.ListLlmModelsRequest, global::Ondewo.Nlu.ListLlmModelsResponse>(serviceImpl.ListLlmModels));
    }

  }
}
#endregion
