// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ondewo/nlu/operations.proto
// </auto-generated>
// Original file comments:
// Copyright 2020-2026 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Ondewo.Nlu {
  /// <summary>
  /// Manages long-running operations with an API service.
  ///
  /// When an API method normally takes long time to complete, it can be designed to return &lt;a href="index.html#ondewo.nlu.Operation">Operation&lt;/a> to the client, and the client can use this interface to receive the real response asynchronously by polling the operation resource, or pass the operation resource to another API (such as Google Cloud Pub/Sub API) to receive the response.  Any API service that returns long-running operations should implement the &lt;code>Operations&lt;/code> interface so developers can have a consistent client experience.
  /// </summary>
  public static partial class Operations
  {
    static readonly string __ServiceName = "ondewo.nlu.Operations";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.ListOperationsRequest> __Marshaller_ondewo_nlu_ListOperationsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.ListOperationsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.ListOperationsResponse> __Marshaller_ondewo_nlu_ListOperationsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.ListOperationsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.GetOperationRequest> __Marshaller_ondewo_nlu_GetOperationRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.GetOperationRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.Operation> __Marshaller_ondewo_nlu_Operation = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.Operation.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.DeleteOperationRequest> __Marshaller_ondewo_nlu_DeleteOperationRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.DeleteOperationRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Google.Protobuf.WellKnownTypes.Empty> __Marshaller_google_protobuf_Empty = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Google.Protobuf.WellKnownTypes.Empty.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.CancelOperationRequest> __Marshaller_ondewo_nlu_CancelOperationRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.CancelOperationRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.StreamRemoteOperationContainerLogsRequest> __Marshaller_ondewo_nlu_StreamRemoteOperationContainerLogsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.StreamRemoteOperationContainerLogsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.RemoteOperationContainerLogLine> __Marshaller_ondewo_nlu_RemoteOperationContainerLogLine = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.RemoteOperationContainerLogLine.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.GetRemoteOperationContainerLogsRequest> __Marshaller_ondewo_nlu_GetRemoteOperationContainerLogsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.GetRemoteOperationContainerLogsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.GetRemoteOperationContainerLogsResponse> __Marshaller_ondewo_nlu_GetRemoteOperationContainerLogsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.GetRemoteOperationContainerLogsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.GetRemoteOperationContainerStatusRequest> __Marshaller_ondewo_nlu_GetRemoteOperationContainerStatusRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.GetRemoteOperationContainerStatusRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.RemoteOperationContainerStatus> __Marshaller_ondewo_nlu_RemoteOperationContainerStatus = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.RemoteOperationContainerStatus.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.ListRemoteOperationContainersRequest> __Marshaller_ondewo_nlu_ListRemoteOperationContainersRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.ListRemoteOperationContainersRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.ListRemoteOperationContainersResponse> __Marshaller_ondewo_nlu_ListRemoteOperationContainersResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.ListRemoteOperationContainersResponse.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.ListOperationsRequest, global::Ondewo.Nlu.ListOperationsResponse> __Method_ListOperations = new grpc::Method<global::Ondewo.Nlu.ListOperationsRequest, global::Ondewo.Nlu.ListOperationsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListOperations",
        __Marshaller_ondewo_nlu_ListOperationsRequest,
        __Marshaller_ondewo_nlu_ListOperationsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.GetOperationRequest, global::Ondewo.Nlu.Operation> __Method_GetOperation = new grpc::Method<global::Ondewo.Nlu.GetOperationRequest, global::Ondewo.Nlu.Operation>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetOperation",
        __Marshaller_ondewo_nlu_GetOperationRequest,
        __Marshaller_ondewo_nlu_Operation);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.DeleteOperationRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_DeleteOperation = new grpc::Method<global::Ondewo.Nlu.DeleteOperationRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "DeleteOperation",
        __Marshaller_ondewo_nlu_DeleteOperationRequest,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.CancelOperationRequest, global::Google.Protobuf.WellKnownTypes.Empty> __Method_CancelOperation = new grpc::Method<global::Ondewo.Nlu.CancelOperationRequest, global::Google.Protobuf.WellKnownTypes.Empty>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CancelOperation",
        __Marshaller_ondewo_nlu_CancelOperationRequest,
        __Marshaller_google_protobuf_Empty);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.StreamRemoteOperationContainerLogsRequest, global::Ondewo.Nlu.RemoteOperationContainerLogLine> __Method_StreamRemoteOperationContainerLogs = new grpc::Method<global::Ondewo.Nlu.StreamRemoteOperationContainerLogsRequest, global::Ondewo.Nlu.RemoteOperationContainerLogLine>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "StreamRemoteOperationContainerLogs",
        __Marshaller_ondewo_nlu_StreamRemoteOperationContainerLogsRequest,
        __Marshaller_ondewo_nlu_RemoteOperationContainerLogLine);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.GetRemoteOperationContainerLogsRequest, global::Ondewo.Nlu.GetRemoteOperationContainerLogsResponse> __Method_GetRemoteOperationContainerLogs = new grpc::Method<global::Ondewo.Nlu.GetRemoteOperationContainerLogsRequest, global::Ondewo.Nlu.GetRemoteOperationContainerLogsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRemoteOperationContainerLogs",
        __Marshaller_ondewo_nlu_GetRemoteOperationContainerLogsRequest,
        __Marshaller_ondewo_nlu_GetRemoteOperationContainerLogsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.GetRemoteOperationContainerStatusRequest, global::Ondewo.Nlu.RemoteOperationContainerStatus> __Method_GetRemoteOperationContainerStatus = new grpc::Method<global::Ondewo.Nlu.GetRemoteOperationContainerStatusRequest, global::Ondewo.Nlu.RemoteOperationContainerStatus>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetRemoteOperationContainerStatus",
        __Marshaller_ondewo_nlu_GetRemoteOperationContainerStatusRequest,
        __Marshaller_ondewo_nlu_RemoteOperationContainerStatus);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.ListRemoteOperationContainersRequest, global::Ondewo.Nlu.ListRemoteOperationContainersResponse> __Method_ListRemoteOperationContainers = new grpc::Method<global::Ondewo.Nlu.ListRemoteOperationContainersRequest, global::Ondewo.Nlu.ListRemoteOperationContainersResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ListRemoteOperationContainers",
        __Marshaller_ondewo_nlu_ListRemoteOperationContainersRequest,
        __Marshaller_ondewo_nlu_ListRemoteOperationContainersResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Ondewo.Nlu.OperationsReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Operations</summary>
    [grpc::BindServiceMethod(typeof(Operations), "BindService")]
    public abstract partial class OperationsBase
    {
      /// <summary>
      /// Lists operations that match the specified filter in the request. If the
      /// server doesn&amp;apos;t support this method, it returns &lt;code>UNIMPLEMENTED&lt;/code>.
      ///&lt;br>
      /// NOTE: the &lt;code>name&lt;/code> binding below allows API services to override the binding
      /// to use different resource name schemes, such as &lt;code>users/*/operations&lt;/code>.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.ListOperationsResponse> ListOperations(global::Ondewo.Nlu.ListOperationsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Gets the latest state of a long-running operation.  Clients can use this
      /// method to poll the operation result at intervals as recommended by the API
      /// service.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.Operation> GetOperation(global::Ondewo.Nlu.GetOperationRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Deletes a long-running operation. This method indicates that the client is
      /// no longer interested in the operation result. It does not cancel the
      /// operation. If the server doesn&amp;apos;t support this method, it returns
      /// &lt;code>google.rpc.Code.UNIMPLEMENTED&lt;/code>
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> DeleteOperation(global::Ondewo.Nlu.DeleteOperationRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Starts asynchronous cancellation on a long-running operation.  The server
      /// makes a best effort to cancel the operation, but success is not
      /// guaranteed.  If the server doesn&amp;apos;t support this method, it returns
      /// &lt;code>google.rpc.Code.UNIMPLEMENTED&lt;/code>.  Clients can use
      /// &lt;a href="index.html#ondewo.nlu.Operations.GetOperation">Operations.GetOperation&lt;/a> or
      /// other methods to verify whether the cancellation succeeded or whether the
      /// operation completed despite cancellation. On successful cancellation,
      /// the operation is not deleted; instead, it becomes an operation with
      /// an &lt;a href="index.html#ondewo.nlu.Operation">Operation.error&lt;/a> value with a &lt;a href="https://developers.google.com/actions-center/reference/grpc-api/status_codes">google.rpc.Status.code&lt;/a>
      /// of 1, corresponding to &lt;code>Code.CANCELLED&lt;/code>.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Google.Protobuf.WellKnownTypes.Empty> CancelOperation(global::Ondewo.Nlu.CancelOperationRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Streams the live container logs of a remote-operation container (LLM evaluation, simulation,
      /// crawl, training) as they are produced, in the manner of &lt;code>docker logs --follow&lt;/code>.
      /// The stream stays open until the container exits or the client disconnects. Each message is a
      /// single parsed log line. Secrets in the log text are redacted server-side before streaming.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task StreamRemoteOperationContainerLogs(global::Ondewo.Nlu.StreamRemoteOperationContainerLogsRequest request, grpc::IServerStreamWriter<global::Ondewo.Nlu.RemoteOperationContainerLogLine> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Returns a bounded, filtered snapshot of a remote-operation container&amp;apos;s logs. Supports a
      /// time window (&lt;code>start_time&lt;/code> / &lt;code>end_time&lt;/code>), a minimum loguru log level,
      /// a regular-expression match on the message, and a cap on the number of returned lines. Secrets
      /// in the log text are redacted server-side before the response is returned.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.GetRemoteOperationContainerLogsResponse> GetRemoteOperationContainerLogs(global::Ondewo.Nlu.GetRemoteOperationContainerLogsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Returns the health and lifecycle status of a remote-operation container: whether it still
      /// exists, whether it is running/exited, its exit code, OOM-kill flag and Docker health status.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.RemoteOperationContainerStatus> GetRemoteOperationContainerStatus(global::Ondewo.Nlu.GetRemoteOperationContainerStatusRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Lists every docker container that a remote operation started (a single operation may run several
      /// containers sequentially, e.g. hardware-check, GPU pre-allocation, build-cache and one training
      /// container per algorithm). When &lt;code>include_sub_operations&lt;/code> is set, the containers of the
      /// operation&amp;apos;s sub-operations are included as well. Each entry carries the container id + name,
      /// its host, lifecycle state and whether logs are still available (live or persisted).
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.ListRemoteOperationContainersResponse> ListRemoteOperationContainers(global::Ondewo.Nlu.ListRemoteOperationContainersRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Operations</summary>
    public partial class OperationsClient : grpc::ClientBase<OperationsClient>
    {
      /// <summary>Creates a new client for Operations</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public OperationsClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Operations that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public OperationsClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected OperationsClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected OperationsClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Lists operations that match the specified filter in the request. If the
      /// server doesn&amp;apos;t support this method, it returns &lt;code>UNIMPLEMENTED&lt;/code>.
      ///&lt;br>
      /// NOTE: the &lt;code>name&lt;/code> binding below allows API services to override the binding
      /// to use different resource name schemes, such as &lt;code>users/*/operations&lt;/code>.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.ListOperationsResponse ListOperations(global::Ondewo.Nlu.ListOperationsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListOperations(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Lists operations that match the specified filter in the request. If the
      /// server doesn&amp;apos;t support this method, it returns &lt;code>UNIMPLEMENTED&lt;/code>.
      ///&lt;br>
      /// NOTE: the &lt;code>name&lt;/code> binding below allows API services to override the binding
      /// to use different resource name schemes, such as &lt;code>users/*/operations&lt;/code>.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.ListOperationsResponse ListOperations(global::Ondewo.Nlu.ListOperationsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListOperations, null, options, request);
      }
      /// <summary>
      /// Lists operations that match the specified filter in the request. If the
      /// server doesn&amp;apos;t support this method, it returns &lt;code>UNIMPLEMENTED&lt;/code>.
      ///&lt;br>
      /// NOTE: the &lt;code>name&lt;/code> binding below allows API services to override the binding
      /// to use different resource name schemes, such as &lt;code>users/*/operations&lt;/code>.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.ListOperationsResponse> ListOperationsAsync(global::Ondewo.Nlu.ListOperationsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListOperationsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Lists operations that match the specified filter in the request. If the
      /// server doesn&amp;apos;t support this method, it returns &lt;code>UNIMPLEMENTED&lt;/code>.
      ///&lt;br>
      /// NOTE: the &lt;code>name&lt;/code> binding below allows API services to override the binding
      /// to use different resource name schemes, such as &lt;code>users/*/operations&lt;/code>.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.ListOperationsResponse> ListOperationsAsync(global::Ondewo.Nlu.ListOperationsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListOperations, null, options, request);
      }
      /// <summary>
      /// Gets the latest state of a long-running operation.  Clients can use this
      /// method to poll the operation result at intervals as recommended by the API
      /// service.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.Operation GetOperation(global::Ondewo.Nlu.GetOperationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetOperation(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Gets the latest state of a long-running operation.  Clients can use this
      /// method to poll the operation result at intervals as recommended by the API
      /// service.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.Operation GetOperation(global::Ondewo.Nlu.GetOperationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetOperation, null, options, request);
      }
      /// <summary>
      /// Gets the latest state of a long-running operation.  Clients can use this
      /// method to poll the operation result at intervals as recommended by the API
      /// service.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.Operation> GetOperationAsync(global::Ondewo.Nlu.GetOperationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetOperationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Gets the latest state of a long-running operation.  Clients can use this
      /// method to poll the operation result at intervals as recommended by the API
      /// service.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.Operation> GetOperationAsync(global::Ondewo.Nlu.GetOperationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetOperation, null, options, request);
      }
      /// <summary>
      /// Deletes a long-running operation. This method indicates that the client is
      /// no longer interested in the operation result. It does not cancel the
      /// operation. If the server doesn&amp;apos;t support this method, it returns
      /// &lt;code>google.rpc.Code.UNIMPLEMENTED&lt;/code>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteOperation(global::Ondewo.Nlu.DeleteOperationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteOperation(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Deletes a long-running operation. This method indicates that the client is
      /// no longer interested in the operation result. It does not cancel the
      /// operation. If the server doesn&amp;apos;t support this method, it returns
      /// &lt;code>google.rpc.Code.UNIMPLEMENTED&lt;/code>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty DeleteOperation(global::Ondewo.Nlu.DeleteOperationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_DeleteOperation, null, options, request);
      }
      /// <summary>
      /// Deletes a long-running operation. This method indicates that the client is
      /// no longer interested in the operation result. It does not cancel the
      /// operation. If the server doesn&amp;apos;t support this method, it returns
      /// &lt;code>google.rpc.Code.UNIMPLEMENTED&lt;/code>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteOperationAsync(global::Ondewo.Nlu.DeleteOperationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return DeleteOperationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Deletes a long-running operation. This method indicates that the client is
      /// no longer interested in the operation result. It does not cancel the
      /// operation. If the server doesn&amp;apos;t support this method, it returns
      /// &lt;code>google.rpc.Code.UNIMPLEMENTED&lt;/code>
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> DeleteOperationAsync(global::Ondewo.Nlu.DeleteOperationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_DeleteOperation, null, options, request);
      }
      /// <summary>
      /// Starts asynchronous cancellation on a long-running operation.  The server
      /// makes a best effort to cancel the operation, but success is not
      /// guaranteed.  If the server doesn&amp;apos;t support this method, it returns
      /// &lt;code>google.rpc.Code.UNIMPLEMENTED&lt;/code>.  Clients can use
      /// &lt;a href="index.html#ondewo.nlu.Operations.GetOperation">Operations.GetOperation&lt;/a> or
      /// other methods to verify whether the cancellation succeeded or whether the
      /// operation completed despite cancellation. On successful cancellation,
      /// the operation is not deleted; instead, it becomes an operation with
      /// an &lt;a href="index.html#ondewo.nlu.Operation">Operation.error&lt;/a> value with a &lt;a href="https://developers.google.com/actions-center/reference/grpc-api/status_codes">google.rpc.Status.code&lt;/a>
      /// of 1, corresponding to &lt;code>Code.CANCELLED&lt;/code>.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty CancelOperation(global::Ondewo.Nlu.CancelOperationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CancelOperation(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Starts asynchronous cancellation on a long-running operation.  The server
      /// makes a best effort to cancel the operation, but success is not
      /// guaranteed.  If the server doesn&amp;apos;t support this method, it returns
      /// &lt;code>google.rpc.Code.UNIMPLEMENTED&lt;/code>.  Clients can use
      /// &lt;a href="index.html#ondewo.nlu.Operations.GetOperation">Operations.GetOperation&lt;/a> or
      /// other methods to verify whether the cancellation succeeded or whether the
      /// operation completed despite cancellation. On successful cancellation,
      /// the operation is not deleted; instead, it becomes an operation with
      /// an &lt;a href="index.html#ondewo.nlu.Operation">Operation.error&lt;/a> value with a &lt;a href="https://developers.google.com/actions-center/reference/grpc-api/status_codes">google.rpc.Status.code&lt;/a>
      /// of 1, corresponding to &lt;code>Code.CANCELLED&lt;/code>.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Google.Protobuf.WellKnownTypes.Empty CancelOperation(global::Ondewo.Nlu.CancelOperationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CancelOperation, null, options, request);
      }
      /// <summary>
      /// Starts asynchronous cancellation on a long-running operation.  The server
      /// makes a best effort to cancel the operation, but success is not
      /// guaranteed.  If the server doesn&amp;apos;t support this method, it returns
      /// &lt;code>google.rpc.Code.UNIMPLEMENTED&lt;/code>.  Clients can use
      /// &lt;a href="index.html#ondewo.nlu.Operations.GetOperation">Operations.GetOperation&lt;/a> or
      /// other methods to verify whether the cancellation succeeded or whether the
      /// operation completed despite cancellation. On successful cancellation,
      /// the operation is not deleted; instead, it becomes an operation with
      /// an &lt;a href="index.html#ondewo.nlu.Operation">Operation.error&lt;/a> value with a &lt;a href="https://developers.google.com/actions-center/reference/grpc-api/status_codes">google.rpc.Status.code&lt;/a>
      /// of 1, corresponding to &lt;code>Code.CANCELLED&lt;/code>.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> CancelOperationAsync(global::Ondewo.Nlu.CancelOperationRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CancelOperationAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Starts asynchronous cancellation on a long-running operation.  The server
      /// makes a best effort to cancel the operation, but success is not
      /// guaranteed.  If the server doesn&amp;apos;t support this method, it returns
      /// &lt;code>google.rpc.Code.UNIMPLEMENTED&lt;/code>.  Clients can use
      /// &lt;a href="index.html#ondewo.nlu.Operations.GetOperation">Operations.GetOperation&lt;/a> or
      /// other methods to verify whether the cancellation succeeded or whether the
      /// operation completed despite cancellation. On successful cancellation,
      /// the operation is not deleted; instead, it becomes an operation with
      /// an &lt;a href="index.html#ondewo.nlu.Operation">Operation.error&lt;/a> value with a &lt;a href="https://developers.google.com/actions-center/reference/grpc-api/status_codes">google.rpc.Status.code&lt;/a>
      /// of 1, corresponding to &lt;code>Code.CANCELLED&lt;/code>.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Google.Protobuf.WellKnownTypes.Empty> CancelOperationAsync(global::Ondewo.Nlu.CancelOperationRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CancelOperation, null, options, request);
      }
      /// <summary>
      /// Streams the live container logs of a remote-operation container (LLM evaluation, simulation,
      /// crawl, training) as they are produced, in the manner of &lt;code>docker logs --follow&lt;/code>.
      /// The stream stays open until the container exits or the client disconnects. Each message is a
      /// single parsed log line. Secrets in the log text are redacted server-side before streaming.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Ondewo.Nlu.RemoteOperationContainerLogLine> StreamRemoteOperationContainerLogs(global::Ondewo.Nlu.StreamRemoteOperationContainerLogsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return StreamRemoteOperationContainerLogs(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Streams the live container logs of a remote-operation container (LLM evaluation, simulation,
      /// crawl, training) as they are produced, in the manner of &lt;code>docker logs --follow&lt;/code>.
      /// The stream stays open until the container exits or the client disconnects. Each message is a
      /// single parsed log line. Secrets in the log text are redacted server-side before streaming.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncServerStreamingCall<global::Ondewo.Nlu.RemoteOperationContainerLogLine> StreamRemoteOperationContainerLogs(global::Ondewo.Nlu.StreamRemoteOperationContainerLogsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_StreamRemoteOperationContainerLogs, null, options, request);
      }
      /// <summary>
      /// Returns a bounded, filtered snapshot of a remote-operation container&amp;apos;s logs. Supports a
      /// time window (&lt;code>start_time&lt;/code> / &lt;code>end_time&lt;/code>), a minimum loguru log level,
      /// a regular-expression match on the message, and a cap on the number of returned lines. Secrets
      /// in the log text are redacted server-side before the response is returned.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.GetRemoteOperationContainerLogsResponse GetRemoteOperationContainerLogs(global::Ondewo.Nlu.GetRemoteOperationContainerLogsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRemoteOperationContainerLogs(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Returns a bounded, filtered snapshot of a remote-operation container&amp;apos;s logs. Supports a
      /// time window (&lt;code>start_time&lt;/code> / &lt;code>end_time&lt;/code>), a minimum loguru log level,
      /// a regular-expression match on the message, and a cap on the number of returned lines. Secrets
      /// in the log text are redacted server-side before the response is returned.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.GetRemoteOperationContainerLogsResponse GetRemoteOperationContainerLogs(global::Ondewo.Nlu.GetRemoteOperationContainerLogsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRemoteOperationContainerLogs, null, options, request);
      }
      /// <summary>
      /// Returns a bounded, filtered snapshot of a remote-operation container&amp;apos;s logs. Supports a
      /// time window (&lt;code>start_time&lt;/code> / &lt;code>end_time&lt;/code>), a minimum loguru log level,
      /// a regular-expression match on the message, and a cap on the number of returned lines. Secrets
      /// in the log text are redacted server-side before the response is returned.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.GetRemoteOperationContainerLogsResponse> GetRemoteOperationContainerLogsAsync(global::Ondewo.Nlu.GetRemoteOperationContainerLogsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRemoteOperationContainerLogsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Returns a bounded, filtered snapshot of a remote-operation container&amp;apos;s logs. Supports a
      /// time window (&lt;code>start_time&lt;/code> / &lt;code>end_time&lt;/code>), a minimum loguru log level,
      /// a regular-expression match on the message, and a cap on the number of returned lines. Secrets
      /// in the log text are redacted server-side before the response is returned.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.GetRemoteOperationContainerLogsResponse> GetRemoteOperationContainerLogsAsync(global::Ondewo.Nlu.GetRemoteOperationContainerLogsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRemoteOperationContainerLogs, null, options, request);
      }
      /// <summary>
      /// Returns the health and lifecycle status of a remote-operation container: whether it still
      /// exists, whether it is running/exited, its exit code, OOM-kill flag and Docker health status.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.RemoteOperationContainerStatus GetRemoteOperationContainerStatus(global::Ondewo.Nlu.GetRemoteOperationContainerStatusRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRemoteOperationContainerStatus(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Returns the health and lifecycle status of a remote-operation container: whether it still
      /// exists, whether it is running/exited, its exit code, OOM-kill flag and Docker health status.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.RemoteOperationContainerStatus GetRemoteOperationContainerStatus(global::Ondewo.Nlu.GetRemoteOperationContainerStatusRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetRemoteOperationContainerStatus, null, options, request);
      }
      /// <summary>
      /// Returns the health and lifecycle status of a remote-operation container: whether it still
      /// exists, whether it is running/exited, its exit code, OOM-kill flag and Docker health status.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.RemoteOperationContainerStatus> GetRemoteOperationContainerStatusAsync(global::Ondewo.Nlu.GetRemoteOperationContainerStatusRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return GetRemoteOperationContainerStatusAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Returns the health and lifecycle status of a remote-operation container: whether it still
      /// exists, whether it is running/exited, its exit code, OOM-kill flag and Docker health status.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.RemoteOperationContainerStatus> GetRemoteOperationContainerStatusAsync(global::Ondewo.Nlu.GetRemoteOperationContainerStatusRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetRemoteOperationContainerStatus, null, options, request);
      }
      /// <summary>
      /// Lists every docker container that a remote operation started (a single operation may run several
      /// containers sequentially, e.g. hardware-check, GPU pre-allocation, build-cache and one training
      /// container per algorithm). When &lt;code>include_sub_operations&lt;/code> is set, the containers of the
      /// operation&amp;apos;s sub-operations are included as well. Each entry carries the container id + name,
      /// its host, lifecycle state and whether logs are still available (live or persisted).
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.ListRemoteOperationContainersResponse ListRemoteOperationContainers(global::Ondewo.Nlu.ListRemoteOperationContainersRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListRemoteOperationContainers(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Lists every docker container that a remote operation started (a single operation may run several
      /// containers sequentially, e.g. hardware-check, GPU pre-allocation, build-cache and one training
      /// container per algorithm). When &lt;code>include_sub_operations&lt;/code> is set, the containers of the
      /// operation&amp;apos;s sub-operations are included as well. Each entry carries the container id + name,
      /// its host, lifecycle state and whether logs are still available (live or persisted).
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.ListRemoteOperationContainersResponse ListRemoteOperationContainers(global::Ondewo.Nlu.ListRemoteOperationContainersRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ListRemoteOperationContainers, null, options, request);
      }
      /// <summary>
      /// Lists every docker container that a remote operation started (a single operation may run several
      /// containers sequentially, e.g. hardware-check, GPU pre-allocation, build-cache and one training
      /// container per algorithm). When &lt;code>include_sub_operations&lt;/code> is set, the containers of the
      /// operation&amp;apos;s sub-operations are included as well. Each entry carries the container id + name,
      /// its host, lifecycle state and whether logs are still available (live or persisted).
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.ListRemoteOperationContainersResponse> ListRemoteOperationContainersAsync(global::Ondewo.Nlu.ListRemoteOperationContainersRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ListRemoteOperationContainersAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Lists every docker container that a remote operation started (a single operation may run several
      /// containers sequentially, e.g. hardware-check, GPU pre-allocation, build-cache and one training
      /// container per algorithm). When &lt;code>include_sub_operations&lt;/code> is set, the containers of the
      /// operation&amp;apos;s sub-operations are included as well. Each entry carries the container id + name,
      /// its host, lifecycle state and whether logs are still available (live or persisted).
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.ListRemoteOperationContainersResponse> ListRemoteOperationContainersAsync(global::Ondewo.Nlu.ListRemoteOperationContainersRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ListRemoteOperationContainers, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override OperationsClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new OperationsClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(OperationsBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ListOperations, serviceImpl.ListOperations)
          .AddMethod(__Method_GetOperation, serviceImpl.GetOperation)
          .AddMethod(__Method_DeleteOperation, serviceImpl.DeleteOperation)
          .AddMethod(__Method_CancelOperation, serviceImpl.CancelOperation)
          .AddMethod(__Method_StreamRemoteOperationContainerLogs, serviceImpl.StreamRemoteOperationContainerLogs)
          .AddMethod(__Method_GetRemoteOperationContainerLogs, serviceImpl.GetRemoteOperationContainerLogs)
          .AddMethod(__Method_GetRemoteOperationContainerStatus, serviceImpl.GetRemoteOperationContainerStatus)
          .AddMethod(__Method_ListRemoteOperationContainers, serviceImpl.ListRemoteOperationContainers).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, OperationsBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ListOperations, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.ListOperationsRequest, global::Ondewo.Nlu.ListOperationsResponse>(serviceImpl.ListOperations));
      serviceBinder.AddMethod(__Method_GetOperation, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.GetOperationRequest, global::Ondewo.Nlu.Operation>(serviceImpl.GetOperation));
      serviceBinder.AddMethod(__Method_DeleteOperation, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.DeleteOperationRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.DeleteOperation));
      serviceBinder.AddMethod(__Method_CancelOperation, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.CancelOperationRequest, global::Google.Protobuf.WellKnownTypes.Empty>(serviceImpl.CancelOperation));
      serviceBinder.AddMethod(__Method_StreamRemoteOperationContainerLogs, serviceImpl == null ? null : new grpc::ServerStreamingServerMethod<global::Ondewo.Nlu.StreamRemoteOperationContainerLogsRequest, global::Ondewo.Nlu.RemoteOperationContainerLogLine>(serviceImpl.StreamRemoteOperationContainerLogs));
      serviceBinder.AddMethod(__Method_GetRemoteOperationContainerLogs, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.GetRemoteOperationContainerLogsRequest, global::Ondewo.Nlu.GetRemoteOperationContainerLogsResponse>(serviceImpl.GetRemoteOperationContainerLogs));
      serviceBinder.AddMethod(__Method_GetRemoteOperationContainerStatus, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.GetRemoteOperationContainerStatusRequest, global::Ondewo.Nlu.RemoteOperationContainerStatus>(serviceImpl.GetRemoteOperationContainerStatus));
      serviceBinder.AddMethod(__Method_ListRemoteOperationContainers, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.ListRemoteOperationContainersRequest, global::Ondewo.Nlu.ListRemoteOperationContainersResponse>(serviceImpl.ListRemoteOperationContainers));
    }

  }
}
#endregion
