// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ondewo/nlu/operation_metadata.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace Ondewo.Nlu {

  /// <summary>Holder for reflection information generated from ondewo/nlu/operation_metadata.proto</summary>
  public static partial class OperationMetadataReflection {

    #region Descriptor
    /// <summary>File descriptor for ondewo/nlu/operation_metadata.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static OperationMetadataReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiNvbmRld28vbmx1L29wZXJhdGlvbl9tZXRhZGF0YS5wcm90bxIKb25kZXdv",
            "Lm5sdRofZ29vZ2xlL3Byb3RvYnVmL3RpbWVzdGFtcC5wcm90byK1CQoRT3Bl",
            "cmF0aW9uTWV0YWRhdGESNAoGc3RhdHVzGAEgASgOMiQub25kZXdvLm5sdS5P",
            "cGVyYXRpb25NZXRhZGF0YS5TdGF0dXMSHQoVcGFyZW50X29wZXJhdGlvbl9u",
            "YW1lGAIgASgJEhsKE3N1Yl9vcGVyYXRpb25fbmFtZXMYAyADKAkSLwoLY3Jl",
            "YXRlX3RpbWUYBCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4K",
            "CnN0YXJ0X3RpbWUYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1w",
            "EiwKCGVuZF90aW1lGAYgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFt",
            "cBIhChlpc19jYW5jZWxsYXRpb25fcmVxdWVzdGVkGAcgASgIEhYKDmNhbmNl",
            "bF9jb21tYW5kGAggASgJEhcKD3VzZXJfaWRfY3JlYXRlZBgJIAEoCRIZChF1",
            "c2VyX2lkX2NhbmNlbGxlZBgKIAEoCRIWCg5wcm9qZWN0X3BhcmVudBgLIAEo",
            "CRJDCg5vcGVyYXRpb25fdHlwZRgMIAEoDjIrLm9uZGV3by5ubHUuT3BlcmF0",
            "aW9uTWV0YWRhdGEuT3BlcmF0aW9uVHlwZRIRCglob3N0X25hbWUYDSABKAkS",
            "EgoKbnVtX3JlcnVucxgOIAEoBRIWCg5tYXhfbnVtX3JlcnVucxgPIAEoBRIT",
            "CgtkZXNjcmlwdGlvbhgQIAEoCRILCgNsb2cYESADKAkSEQoJbG9nX2xpbWl0",
            "GBIgASgFEi4KCmNyZWF0ZWRfYXQYEyABKAsyGi5nb29nbGUucHJvdG9idWYu",
            "VGltZXN0YW1wEi8KC21vZGlmaWVkX2F0GBQgASgLMhouZ29vZ2xlLnByb3Rv",
            "YnVmLlRpbWVzdGFtcBISCgpjcmVhdGVkX2J5GBUgASgJEhMKC21vZGlmaWVk",
            "X2J5GBYgASgJImcKBlN0YXR1cxIWChJTVEFUVVNfVU5TUEVDSUZJRUQQABIP",
            "CgtOT1RfU1RBUlRFRBABEg8KC0lOX1BST0dSRVNTEAISCAoERE9ORRADEg0K",
            "CUNBTkNFTExFRBAEEgoKBkZBSUxFRBAFIusCCg1PcGVyYXRpb25UeXBlEh4K",
            "Gk9QRVJBVElPTl9UWVBFX1VOU1BFQ0lGSUVEEAASEAoMQ1JFQVRFX0FHRU5U",
            "EAESEAoMSU1QT1JUX0FHRU5UEAISEAoMRVhQT1JUX0FHRU5UEAMSEAoMREVM",
            "RVRFX0FHRU5UEAQSEQoNUkVTVE9SRV9BR0VOVBAFEhUKEUJVSUxEX0FHRU5U",
            "X0NBQ0hFEAYSDwoLVFJBSU5fQUdFTlQQBxIaChZFWFBPUlRfQkVOQ0hNQVJL",
            "X0FHRU5UEAgSDwoLSU5ERVhfQUdFTlQQCRITCg9SVU5fUkFHX0NSQVdMRVIQ",
            "ChIlCiFBRERfUkFHX0NSQVdMRVJfUkVTVUxUX1RPX0RBVEFTRVQQCxIqCiZS",
            "RU1PVkVfUkFHX0NSQVdMRVJfUkVTVUxUX0ZST01fREFUQVNFVBAMEiIKHkNI",
            "QU5HRV9EQVRBU0VUX0VNQkVERElOR19NT0RFTBANYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::Google.Protobuf.WellKnownTypes.TimestampReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::Ondewo.Nlu.OperationMetadata), global::Ondewo.Nlu.OperationMetadata.Parser, new[]{ "Status", "ParentOperationName", "SubOperationNames", "CreateTime", "StartTime", "EndTime", "IsCancellationRequested", "CancelCommand", "UserIdCreated", "UserIdCancelled", "ProjectParent", "OperationType", "HostName", "NumReruns", "MaxNumReruns", "Description", "Log", "LogLimit", "CreatedAt", "ModifiedAt", "CreatedBy", "ModifiedBy" }, null, new[]{ typeof(global::Ondewo.Nlu.OperationMetadata.Types.Status), typeof(global::Ondewo.Nlu.OperationMetadata.Types.OperationType) }, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  /// <summary>
  /// Represents the metadata of the long-running operation that can be a parent operation for sub-operations or
  /// can be a sub-operation itself
  /// </summary>
  [global::System.Diagnostics.DebuggerDisplayAttribute("{ToString(),nq}")]
  public sealed partial class OperationMetadata : pb::IMessage<OperationMetadata>
  #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      , pb::IBufferMessage
  #endif
  {
    private static readonly pb::MessageParser<OperationMetadata> _parser = new pb::MessageParser<OperationMetadata>(() => new OperationMetadata());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pb::MessageParser<OperationMetadata> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::Ondewo.Nlu.OperationMetadataReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OperationMetadata() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OperationMetadata(OperationMetadata other) : this() {
      status_ = other.status_;
      parentOperationName_ = other.parentOperationName_;
      subOperationNames_ = other.subOperationNames_.Clone();
      createTime_ = other.createTime_ != null ? other.createTime_.Clone() : null;
      startTime_ = other.startTime_ != null ? other.startTime_.Clone() : null;
      endTime_ = other.endTime_ != null ? other.endTime_.Clone() : null;
      isCancellationRequested_ = other.isCancellationRequested_;
      cancelCommand_ = other.cancelCommand_;
      userIdCreated_ = other.userIdCreated_;
      userIdCancelled_ = other.userIdCancelled_;
      projectParent_ = other.projectParent_;
      operationType_ = other.operationType_;
      hostName_ = other.hostName_;
      numReruns_ = other.numReruns_;
      maxNumReruns_ = other.maxNumReruns_;
      description_ = other.description_;
      log_ = other.log_.Clone();
      logLimit_ = other.logLimit_;
      createdAt_ = other.createdAt_ != null ? other.createdAt_.Clone() : null;
      modifiedAt_ = other.modifiedAt_ != null ? other.modifiedAt_.Clone() : null;
      createdBy_ = other.createdBy_;
      modifiedBy_ = other.modifiedBy_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public OperationMetadata Clone() {
      return new OperationMetadata(this);
    }

    /// <summary>Field number for the "status" field.</summary>
    public const int StatusFieldNumber = 1;
    private global::Ondewo.Nlu.OperationMetadata.Types.Status status_ = global::Ondewo.Nlu.OperationMetadata.Types.Status.Unspecified;
    /// <summary>
    /// long-running operation status code
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ondewo.Nlu.OperationMetadata.Types.Status Status {
      get { return status_; }
      set {
        status_ = value;
      }
    }

    /// <summary>Field number for the "parent_operation_name" field.</summary>
    public const int ParentOperationNameFieldNumber = 2;
    private string parentOperationName_ = "";
    /// <summary>
    /// optional parent operation name
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ParentOperationName {
      get { return parentOperationName_; }
      set {
        parentOperationName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "sub_operation_names" field.</summary>
    public const int SubOperationNamesFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_subOperationNames_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> subOperationNames_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// list of the sub-operations&amp;apos; names of the operation
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> SubOperationNames {
      get { return subOperationNames_; }
    }

    /// <summary>Field number for the "create_time" field.</summary>
    public const int CreateTimeFieldNumber = 4;
    private global::Google.Protobuf.WellKnownTypes.Timestamp createTime_;
    /// <summary>
    /// the time the operation was submitted.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CreateTime {
      get { return createTime_; }
      set {
        createTime_ = value;
      }
    }

    /// <summary>Field number for the "start_time" field.</summary>
    public const int StartTimeFieldNumber = 5;
    private global::Google.Protobuf.WellKnownTypes.Timestamp startTime_;
    /// <summary>
    /// the time operation processing started.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp StartTime {
      get { return startTime_; }
      set {
        startTime_ = value;
      }
    }

    /// <summary>Field number for the "end_time" field.</summary>
    public const int EndTimeFieldNumber = 6;
    private global::Google.Protobuf.WellKnownTypes.Timestamp endTime_;
    /// <summary>
    /// the time operation processing completed.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp EndTime {
      get { return endTime_; }
      set {
        endTime_ = value;
      }
    }

    /// <summary>Field number for the "is_cancellation_requested" field.</summary>
    public const int IsCancellationRequestedFieldNumber = 7;
    private bool isCancellationRequested_;
    /// <summary>
    /// indicates whether a request to cancel this operation has been made.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool IsCancellationRequested {
      get { return isCancellationRequested_; }
      set {
        isCancellationRequested_ = value;
      }
    }

    /// <summary>Field number for the "cancel_command" field.</summary>
    public const int CancelCommandFieldNumber = 8;
    private string cancelCommand_ = "";
    /// <summary>
    /// command executed at cancel operation
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CancelCommand {
      get { return cancelCommand_; }
      set {
        cancelCommand_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user_id_created" field.</summary>
    public const int UserIdCreatedFieldNumber = 9;
    private string userIdCreated_ = "";
    /// <summary>
    /// id of the user who created the operation
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserIdCreated {
      get { return userIdCreated_; }
      set {
        userIdCreated_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "user_id_cancelled" field.</summary>
    public const int UserIdCancelledFieldNumber = 10;
    private string userIdCancelled_ = "";
    /// <summary>
    /// id of the user who cancelled the operation
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string UserIdCancelled {
      get { return userIdCancelled_; }
      set {
        userIdCancelled_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "project_parent" field.</summary>
    public const int ProjectParentFieldNumber = 11;
    private string projectParent_ = "";
    /// <summary>
    /// project parent name, e.g. &amp;quot;projects/pepper/agent&amp;quot;
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ProjectParent {
      get { return projectParent_; }
      set {
        projectParent_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "operation_type" field.</summary>
    public const int OperationTypeFieldNumber = 12;
    private global::Ondewo.Nlu.OperationMetadata.Types.OperationType operationType_ = global::Ondewo.Nlu.OperationMetadata.Types.OperationType.Unspecified;
    /// <summary>
    /// operation type
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Ondewo.Nlu.OperationMetadata.Types.OperationType OperationType {
      get { return operationType_; }
      set {
        operationType_ = value;
      }
    }

    /// <summary>Field number for the "host_name" field.</summary>
    public const int HostNameFieldNumber = 13;
    private string hostName_ = "";
    /// <summary>
    /// name of the host where the operation was executed
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string HostName {
      get { return hostName_; }
      set {
        hostName_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "num_reruns" field.</summary>
    public const int NumRerunsFieldNumber = 14;
    private int numReruns_;
    /// <summary>
    /// number of times the operation was re-run
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int NumReruns {
      get { return numReruns_; }
      set {
        numReruns_ = value;
      }
    }

    /// <summary>Field number for the "max_num_reruns" field.</summary>
    public const int MaxNumRerunsFieldNumber = 15;
    private int maxNumReruns_;
    /// <summary>
    /// maximum number of re-runs in case the operation fails
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int MaxNumReruns {
      get { return maxNumReruns_; }
      set {
        maxNumReruns_ = value;
      }
    }

    /// <summary>Field number for the "description" field.</summary>
    public const int DescriptionFieldNumber = 16;
    private string description_ = "";
    /// <summary>
    /// description, normally needed for sub operations when type is OPERATION_TYPE_UNSPECIFIED
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string Description {
      get { return description_; }
      set {
        description_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "log" field.</summary>
    public const int LogFieldNumber = 17;
    private static readonly pb::FieldCodec<string> _repeated_log_codec
        = pb::FieldCodec.ForString(138);
    private readonly pbc::RepeatedField<string> log_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// The log output of an operation
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public pbc::RepeatedField<string> Log {
      get { return log_; }
    }

    /// <summary>Field number for the "log_limit" field.</summary>
    public const int LogLimitFieldNumber = 18;
    private int logLimit_;
    /// <summary>
    /// The log output of an operation limited to the last x log entries
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int LogLimit {
      get { return logLimit_; }
      set {
        logLimit_ = value;
      }
    }

    /// <summary>Field number for the "created_at" field.</summary>
    public const int CreatedAtFieldNumber = 19;
    private global::Google.Protobuf.WellKnownTypes.Timestamp createdAt_;
    /// <summary>
    /// Creation date and time. Read-only field.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp CreatedAt {
      get { return createdAt_; }
      set {
        createdAt_ = value;
      }
    }

    /// <summary>Field number for the "modified_at" field.</summary>
    public const int ModifiedAtFieldNumber = 20;
    private global::Google.Protobuf.WellKnownTypes.Timestamp modifiedAt_;
    /// <summary>
    /// Modification date and time. Read-only field.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public global::Google.Protobuf.WellKnownTypes.Timestamp ModifiedAt {
      get { return modifiedAt_; }
      set {
        modifiedAt_ = value;
      }
    }

    /// <summary>Field number for the "created_by" field.</summary>
    public const int CreatedByFieldNumber = 21;
    private string createdBy_ = "";
    /// <summary>
    /// User id in form of a valid UUID.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string CreatedBy {
      get { return createdBy_; }
      set {
        createdBy_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "modified_by" field.</summary>
    public const int ModifiedByFieldNumber = 22;
    private string modifiedBy_ = "";
    /// <summary>
    /// User id in form of a valid UUID.
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public string ModifiedBy {
      get { return modifiedBy_; }
      set {
        modifiedBy_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override bool Equals(object other) {
      return Equals(other as OperationMetadata);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public bool Equals(OperationMetadata other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Status != other.Status) return false;
      if (ParentOperationName != other.ParentOperationName) return false;
      if(!subOperationNames_.Equals(other.subOperationNames_)) return false;
      if (!object.Equals(CreateTime, other.CreateTime)) return false;
      if (!object.Equals(StartTime, other.StartTime)) return false;
      if (!object.Equals(EndTime, other.EndTime)) return false;
      if (IsCancellationRequested != other.IsCancellationRequested) return false;
      if (CancelCommand != other.CancelCommand) return false;
      if (UserIdCreated != other.UserIdCreated) return false;
      if (UserIdCancelled != other.UserIdCancelled) return false;
      if (ProjectParent != other.ProjectParent) return false;
      if (OperationType != other.OperationType) return false;
      if (HostName != other.HostName) return false;
      if (NumReruns != other.NumReruns) return false;
      if (MaxNumReruns != other.MaxNumReruns) return false;
      if (Description != other.Description) return false;
      if(!log_.Equals(other.log_)) return false;
      if (LogLimit != other.LogLimit) return false;
      if (!object.Equals(CreatedAt, other.CreatedAt)) return false;
      if (!object.Equals(ModifiedAt, other.ModifiedAt)) return false;
      if (CreatedBy != other.CreatedBy) return false;
      if (ModifiedBy != other.ModifiedBy) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override int GetHashCode() {
      int hash = 1;
      if (Status != global::Ondewo.Nlu.OperationMetadata.Types.Status.Unspecified) hash ^= Status.GetHashCode();
      if (ParentOperationName.Length != 0) hash ^= ParentOperationName.GetHashCode();
      hash ^= subOperationNames_.GetHashCode();
      if (createTime_ != null) hash ^= CreateTime.GetHashCode();
      if (startTime_ != null) hash ^= StartTime.GetHashCode();
      if (endTime_ != null) hash ^= EndTime.GetHashCode();
      if (IsCancellationRequested != false) hash ^= IsCancellationRequested.GetHashCode();
      if (CancelCommand.Length != 0) hash ^= CancelCommand.GetHashCode();
      if (UserIdCreated.Length != 0) hash ^= UserIdCreated.GetHashCode();
      if (UserIdCancelled.Length != 0) hash ^= UserIdCancelled.GetHashCode();
      if (ProjectParent.Length != 0) hash ^= ProjectParent.GetHashCode();
      if (OperationType != global::Ondewo.Nlu.OperationMetadata.Types.OperationType.Unspecified) hash ^= OperationType.GetHashCode();
      if (HostName.Length != 0) hash ^= HostName.GetHashCode();
      if (NumReruns != 0) hash ^= NumReruns.GetHashCode();
      if (MaxNumReruns != 0) hash ^= MaxNumReruns.GetHashCode();
      if (Description.Length != 0) hash ^= Description.GetHashCode();
      hash ^= log_.GetHashCode();
      if (LogLimit != 0) hash ^= LogLimit.GetHashCode();
      if (createdAt_ != null) hash ^= CreatedAt.GetHashCode();
      if (modifiedAt_ != null) hash ^= ModifiedAt.GetHashCode();
      if (CreatedBy.Length != 0) hash ^= CreatedBy.GetHashCode();
      if (ModifiedBy.Length != 0) hash ^= ModifiedBy.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void WriteTo(pb::CodedOutputStream output) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      output.WriteRawMessage(this);
    #else
      if (Status != global::Ondewo.Nlu.OperationMetadata.Types.Status.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (ParentOperationName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ParentOperationName);
      }
      subOperationNames_.WriteTo(output, _repeated_subOperationNames_codec);
      if (createTime_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(CreateTime);
      }
      if (startTime_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(StartTime);
      }
      if (endTime_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(EndTime);
      }
      if (IsCancellationRequested != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsCancellationRequested);
      }
      if (CancelCommand.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(CancelCommand);
      }
      if (UserIdCreated.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(UserIdCreated);
      }
      if (UserIdCancelled.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(UserIdCancelled);
      }
      if (ProjectParent.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(ProjectParent);
      }
      if (OperationType != global::Ondewo.Nlu.OperationMetadata.Types.OperationType.Unspecified) {
        output.WriteRawTag(96);
        output.WriteEnum((int) OperationType);
      }
      if (HostName.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(HostName);
      }
      if (NumReruns != 0) {
        output.WriteRawTag(112);
        output.WriteInt32(NumReruns);
      }
      if (MaxNumReruns != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(MaxNumReruns);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(Description);
      }
      log_.WriteTo(output, _repeated_log_codec);
      if (LogLimit != 0) {
        output.WriteRawTag(144, 1);
        output.WriteInt32(LogLimit);
      }
      if (createdAt_ != null) {
        output.WriteRawTag(154, 1);
        output.WriteMessage(CreatedAt);
      }
      if (modifiedAt_ != null) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(ModifiedAt);
      }
      if (CreatedBy.Length != 0) {
        output.WriteRawTag(170, 1);
        output.WriteString(CreatedBy);
      }
      if (ModifiedBy.Length != 0) {
        output.WriteRawTag(178, 1);
        output.WriteString(ModifiedBy);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalWriteTo(ref pb::WriteContext output) {
      if (Status != global::Ondewo.Nlu.OperationMetadata.Types.Status.Unspecified) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Status);
      }
      if (ParentOperationName.Length != 0) {
        output.WriteRawTag(18);
        output.WriteString(ParentOperationName);
      }
      subOperationNames_.WriteTo(ref output, _repeated_subOperationNames_codec);
      if (createTime_ != null) {
        output.WriteRawTag(34);
        output.WriteMessage(CreateTime);
      }
      if (startTime_ != null) {
        output.WriteRawTag(42);
        output.WriteMessage(StartTime);
      }
      if (endTime_ != null) {
        output.WriteRawTag(50);
        output.WriteMessage(EndTime);
      }
      if (IsCancellationRequested != false) {
        output.WriteRawTag(56);
        output.WriteBool(IsCancellationRequested);
      }
      if (CancelCommand.Length != 0) {
        output.WriteRawTag(66);
        output.WriteString(CancelCommand);
      }
      if (UserIdCreated.Length != 0) {
        output.WriteRawTag(74);
        output.WriteString(UserIdCreated);
      }
      if (UserIdCancelled.Length != 0) {
        output.WriteRawTag(82);
        output.WriteString(UserIdCancelled);
      }
      if (ProjectParent.Length != 0) {
        output.WriteRawTag(90);
        output.WriteString(ProjectParent);
      }
      if (OperationType != global::Ondewo.Nlu.OperationMetadata.Types.OperationType.Unspecified) {
        output.WriteRawTag(96);
        output.WriteEnum((int) OperationType);
      }
      if (HostName.Length != 0) {
        output.WriteRawTag(106);
        output.WriteString(HostName);
      }
      if (NumReruns != 0) {
        output.WriteRawTag(112);
        output.WriteInt32(NumReruns);
      }
      if (MaxNumReruns != 0) {
        output.WriteRawTag(120);
        output.WriteInt32(MaxNumReruns);
      }
      if (Description.Length != 0) {
        output.WriteRawTag(130, 1);
        output.WriteString(Description);
      }
      log_.WriteTo(ref output, _repeated_log_codec);
      if (LogLimit != 0) {
        output.WriteRawTag(144, 1);
        output.WriteInt32(LogLimit);
      }
      if (createdAt_ != null) {
        output.WriteRawTag(154, 1);
        output.WriteMessage(CreatedAt);
      }
      if (modifiedAt_ != null) {
        output.WriteRawTag(162, 1);
        output.WriteMessage(ModifiedAt);
      }
      if (CreatedBy.Length != 0) {
        output.WriteRawTag(170, 1);
        output.WriteString(CreatedBy);
      }
      if (ModifiedBy.Length != 0) {
        output.WriteRawTag(178, 1);
        output.WriteString(ModifiedBy);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(ref output);
      }
    }
    #endif

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public int CalculateSize() {
      int size = 0;
      if (Status != global::Ondewo.Nlu.OperationMetadata.Types.Status.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Status);
      }
      if (ParentOperationName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ParentOperationName);
      }
      size += subOperationNames_.CalculateSize(_repeated_subOperationNames_codec);
      if (createTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CreateTime);
      }
      if (startTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(StartTime);
      }
      if (endTime_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(EndTime);
      }
      if (IsCancellationRequested != false) {
        size += 1 + 1;
      }
      if (CancelCommand.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(CancelCommand);
      }
      if (UserIdCreated.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserIdCreated);
      }
      if (UserIdCancelled.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(UserIdCancelled);
      }
      if (ProjectParent.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ProjectParent);
      }
      if (OperationType != global::Ondewo.Nlu.OperationMetadata.Types.OperationType.Unspecified) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) OperationType);
      }
      if (HostName.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(HostName);
      }
      if (NumReruns != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(NumReruns);
      }
      if (MaxNumReruns != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(MaxNumReruns);
      }
      if (Description.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(Description);
      }
      size += log_.CalculateSize(_repeated_log_codec);
      if (LogLimit != 0) {
        size += 2 + pb::CodedOutputStream.ComputeInt32Size(LogLimit);
      }
      if (createdAt_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(CreatedAt);
      }
      if (modifiedAt_ != null) {
        size += 2 + pb::CodedOutputStream.ComputeMessageSize(ModifiedAt);
      }
      if (CreatedBy.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(CreatedBy);
      }
      if (ModifiedBy.Length != 0) {
        size += 2 + pb::CodedOutputStream.ComputeStringSize(ModifiedBy);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(OperationMetadata other) {
      if (other == null) {
        return;
      }
      if (other.Status != global::Ondewo.Nlu.OperationMetadata.Types.Status.Unspecified) {
        Status = other.Status;
      }
      if (other.ParentOperationName.Length != 0) {
        ParentOperationName = other.ParentOperationName;
      }
      subOperationNames_.Add(other.subOperationNames_);
      if (other.createTime_ != null) {
        if (createTime_ == null) {
          CreateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CreateTime.MergeFrom(other.CreateTime);
      }
      if (other.startTime_ != null) {
        if (startTime_ == null) {
          StartTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        StartTime.MergeFrom(other.StartTime);
      }
      if (other.endTime_ != null) {
        if (endTime_ == null) {
          EndTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        EndTime.MergeFrom(other.EndTime);
      }
      if (other.IsCancellationRequested != false) {
        IsCancellationRequested = other.IsCancellationRequested;
      }
      if (other.CancelCommand.Length != 0) {
        CancelCommand = other.CancelCommand;
      }
      if (other.UserIdCreated.Length != 0) {
        UserIdCreated = other.UserIdCreated;
      }
      if (other.UserIdCancelled.Length != 0) {
        UserIdCancelled = other.UserIdCancelled;
      }
      if (other.ProjectParent.Length != 0) {
        ProjectParent = other.ProjectParent;
      }
      if (other.OperationType != global::Ondewo.Nlu.OperationMetadata.Types.OperationType.Unspecified) {
        OperationType = other.OperationType;
      }
      if (other.HostName.Length != 0) {
        HostName = other.HostName;
      }
      if (other.NumReruns != 0) {
        NumReruns = other.NumReruns;
      }
      if (other.MaxNumReruns != 0) {
        MaxNumReruns = other.MaxNumReruns;
      }
      if (other.Description.Length != 0) {
        Description = other.Description;
      }
      log_.Add(other.log_);
      if (other.LogLimit != 0) {
        LogLimit = other.LogLimit;
      }
      if (other.createdAt_ != null) {
        if (createdAt_ == null) {
          CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        CreatedAt.MergeFrom(other.CreatedAt);
      }
      if (other.modifiedAt_ != null) {
        if (modifiedAt_ == null) {
          ModifiedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
        }
        ModifiedAt.MergeFrom(other.ModifiedAt);
      }
      if (other.CreatedBy.Length != 0) {
        CreatedBy = other.CreatedBy;
      }
      if (other.ModifiedBy.Length != 0) {
        ModifiedBy = other.ModifiedBy;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public void MergeFrom(pb::CodedInputStream input) {
    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
      input.ReadRawMessage(this);
    #else
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            Status = (global::Ondewo.Nlu.OperationMetadata.Types.Status) input.ReadEnum();
            break;
          }
          case 18: {
            ParentOperationName = input.ReadString();
            break;
          }
          case 26: {
            subOperationNames_.AddEntriesFrom(input, _repeated_subOperationNames_codec);
            break;
          }
          case 34: {
            if (createTime_ == null) {
              CreateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreateTime);
            break;
          }
          case 42: {
            if (startTime_ == null) {
              StartTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(StartTime);
            break;
          }
          case 50: {
            if (endTime_ == null) {
              EndTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(EndTime);
            break;
          }
          case 56: {
            IsCancellationRequested = input.ReadBool();
            break;
          }
          case 66: {
            CancelCommand = input.ReadString();
            break;
          }
          case 74: {
            UserIdCreated = input.ReadString();
            break;
          }
          case 82: {
            UserIdCancelled = input.ReadString();
            break;
          }
          case 90: {
            ProjectParent = input.ReadString();
            break;
          }
          case 96: {
            OperationType = (global::Ondewo.Nlu.OperationMetadata.Types.OperationType) input.ReadEnum();
            break;
          }
          case 106: {
            HostName = input.ReadString();
            break;
          }
          case 112: {
            NumReruns = input.ReadInt32();
            break;
          }
          case 120: {
            MaxNumReruns = input.ReadInt32();
            break;
          }
          case 130: {
            Description = input.ReadString();
            break;
          }
          case 138: {
            log_.AddEntriesFrom(input, _repeated_log_codec);
            break;
          }
          case 144: {
            LogLimit = input.ReadInt32();
            break;
          }
          case 154: {
            if (createdAt_ == null) {
              CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreatedAt);
            break;
          }
          case 162: {
            if (modifiedAt_ == null) {
              ModifiedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ModifiedAt);
            break;
          }
          case 170: {
            CreatedBy = input.ReadString();
            break;
          }
          case 178: {
            ModifiedBy = input.ReadString();
            break;
          }
        }
      }
    #endif
    }

    #if !GOOGLE_PROTOBUF_REFSTRUCT_COMPATIBILITY_MODE
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    void pb::IBufferMessage.InternalMergeFrom(ref pb::ParseContext input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
      if ((tag & 7) == 4) {
        // Abort on any end group tag.
        return;
      }
      switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, ref input);
            break;
          case 8: {
            Status = (global::Ondewo.Nlu.OperationMetadata.Types.Status) input.ReadEnum();
            break;
          }
          case 18: {
            ParentOperationName = input.ReadString();
            break;
          }
          case 26: {
            subOperationNames_.AddEntriesFrom(ref input, _repeated_subOperationNames_codec);
            break;
          }
          case 34: {
            if (createTime_ == null) {
              CreateTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreateTime);
            break;
          }
          case 42: {
            if (startTime_ == null) {
              StartTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(StartTime);
            break;
          }
          case 50: {
            if (endTime_ == null) {
              EndTime = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(EndTime);
            break;
          }
          case 56: {
            IsCancellationRequested = input.ReadBool();
            break;
          }
          case 66: {
            CancelCommand = input.ReadString();
            break;
          }
          case 74: {
            UserIdCreated = input.ReadString();
            break;
          }
          case 82: {
            UserIdCancelled = input.ReadString();
            break;
          }
          case 90: {
            ProjectParent = input.ReadString();
            break;
          }
          case 96: {
            OperationType = (global::Ondewo.Nlu.OperationMetadata.Types.OperationType) input.ReadEnum();
            break;
          }
          case 106: {
            HostName = input.ReadString();
            break;
          }
          case 112: {
            NumReruns = input.ReadInt32();
            break;
          }
          case 120: {
            MaxNumReruns = input.ReadInt32();
            break;
          }
          case 130: {
            Description = input.ReadString();
            break;
          }
          case 138: {
            log_.AddEntriesFrom(ref input, _repeated_log_codec);
            break;
          }
          case 144: {
            LogLimit = input.ReadInt32();
            break;
          }
          case 154: {
            if (createdAt_ == null) {
              CreatedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(CreatedAt);
            break;
          }
          case 162: {
            if (modifiedAt_ == null) {
              ModifiedAt = new global::Google.Protobuf.WellKnownTypes.Timestamp();
            }
            input.ReadMessage(ModifiedAt);
            break;
          }
          case 170: {
            CreatedBy = input.ReadString();
            break;
          }
          case 178: {
            ModifiedBy = input.ReadString();
            break;
          }
        }
      }
    }
    #endif

    #region Nested types
    /// <summary>Container for nested types declared in the OperationMetadata message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    [global::System.CodeDom.Compiler.GeneratedCode("protoc", null)]
    public static partial class Types {
      /// <summary>
      /// Structure to set status of operation.
      /// An operation may not be started if NOT_STARTED is set, in progress if IN_PROGRESS, finished if DONE, interrupted if CANCELED or failed if FAILED.
      /// </summary>
      public enum Status {
        /// <summary>
        /// unspecified status code
        /// </summary>
        [pbr::OriginalName("STATUS_UNSPECIFIED")] Unspecified = 0,
        /// <summary>
        /// operation haven&amp;apos;t started yet
        /// </summary>
        [pbr::OriginalName("NOT_STARTED")] NotStarted = 1,
        /// <summary>
        /// operation currently in progress
        /// </summary>
        [pbr::OriginalName("IN_PROGRESS")] InProgress = 2,
        /// <summary>
        /// operation has completed without any error
        /// </summary>
        [pbr::OriginalName("DONE")] Done = 3,
        /// <summary>
        /// operation has completed with cancellation by user
        /// </summary>
        [pbr::OriginalName("CANCELLED")] Cancelled = 4,
        /// <summary>
        /// operation has completed with errors
        /// </summary>
        [pbr::OriginalName("FAILED")] Failed = 5,
      }

      /// <summary>
      /// Type of operation.
      /// It can be creating, importing, exporting, deleting, restoring, building cache, training or exporting benchmark an agent
      /// </summary>
      public enum OperationType {
        /// <summary>
        /// unspecified operation type
        /// </summary>
        [pbr::OriginalName("OPERATION_TYPE_UNSPECIFIED")] Unspecified = 0,
        /// <summary>
        /// create a new agent with specified configuration
        /// </summary>
        [pbr::OriginalName("CREATE_AGENT")] CreateAgent = 1,
        /// <summary>
        /// import agent from a zip file
        /// </summary>
        [pbr::OriginalName("IMPORT_AGENT")] ImportAgent = 2,
        /// <summary>
        /// export agent to a zip file
        /// </summary>
        [pbr::OriginalName("EXPORT_AGENT")] ExportAgent = 3,
        /// <summary>
        /// delete agent
        /// </summary>
        [pbr::OriginalName("DELETE_AGENT")] DeleteAgent = 4,
        /// <summary>
        /// restore agent
        /// </summary>
        [pbr::OriginalName("RESTORE_AGENT")] RestoreAgent = 5,
        /// <summary>
        /// build agent cache
        /// </summary>
        [pbr::OriginalName("BUILD_AGENT_CACHE")] BuildAgentCache = 6,
        /// <summary>
        /// train agent
        /// </summary>
        [pbr::OriginalName("TRAIN_AGENT")] TrainAgent = 7,
        /// <summary>
        /// export benchmark agent to a zip file
        /// </summary>
        [pbr::OriginalName("EXPORT_BENCHMARK_AGENT")] ExportBenchmarkAgent = 8,
        /// <summary>
        /// force loading agent data for full text search
        /// </summary>
        [pbr::OriginalName("INDEX_AGENT")] IndexAgent = 9,
        /// <summary>
        /// run a rag crawler
        /// </summary>
        [pbr::OriginalName("RUN_RAG_CRAWLER")] RunRagCrawler = 10,
        /// <summary>
        /// add a rag crawler result to a dataset
        /// </summary>
        [pbr::OriginalName("ADD_RAG_CRAWLER_RESULT_TO_DATASET")] AddRagCrawlerResultToDataset = 11,
        /// <summary>
        /// remove a rag crawler result from a dataset
        /// </summary>
        [pbr::OriginalName("REMOVE_RAG_CRAWLER_RESULT_FROM_DATASET")] RemoveRagCrawlerResultFromDataset = 12,
        /// <summary>
        /// change the embedding model of dataset that already contains parsed documents
        /// </summary>
        [pbr::OriginalName("CHANGE_DATASET_EMBEDDING_MODEL")] ChangeDatasetEmbeddingModel = 13,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
