// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ondewo/nlu/utility.proto
// </auto-generated>
// Original file comments:
// Copyright 2018 Google Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Modifications Copyright 2020-2026 ONDEWO GmbH
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
#pragma warning disable 0414, 1591, 8981, 0612
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Ondewo.Nlu {
  /// <summary>
  /// This is collection of utility endpoints, intended to language-independent operations, such as code checks, regex checks, etc. Holds a collection of utility functions
  /// </summary>
  public static partial class Utilities
  {
    static readonly string __ServiceName = "ondewo.nlu.Utilities";

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static void __Helper_SerializeMessage(global::Google.Protobuf.IMessage message, grpc::SerializationContext context)
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (message is global::Google.Protobuf.IBufferMessage)
      {
        context.SetPayloadLength(message.CalculateSize());
        global::Google.Protobuf.MessageExtensions.WriteTo(message, context.GetBufferWriter());
        context.Complete();
        return;
      }
      #endif
      context.Complete(global::Google.Protobuf.MessageExtensions.ToByteArray(message));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static class __Helper_MessageCache<T>
    {
      public static readonly bool IsBufferMessage = global::System.Reflection.IntrospectionExtensions.GetTypeInfo(typeof(global::Google.Protobuf.IBufferMessage)).IsAssignableFrom(typeof(T));
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static T __Helper_DeserializeMessage<T>(grpc::DeserializationContext context, global::Google.Protobuf.MessageParser<T> parser) where T : global::Google.Protobuf.IMessage<T>
    {
      #if !GRPC_DISABLE_PROTOBUF_BUFFER_SERIALIZATION
      if (__Helper_MessageCache<T>.IsBufferMessage)
      {
        return parser.ParseFrom(context.PayloadAsReadOnlySequence());
      }
      #endif
      return parser.ParseFrom(context.PayloadAsNewBuffer());
    }

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.ValidateRegexRequest> __Marshaller_ondewo_nlu_ValidateRegexRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.ValidateRegexRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.ValidateRegexResponse> __Marshaller_ondewo_nlu_ValidateRegexResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.ValidateRegexResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.ValidateEmbeddedRegexRequest> __Marshaller_ondewo_nlu_ValidateEmbeddedRegexRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.ValidateEmbeddedRegexRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.ValidateEmbeddedRegexResponse> __Marshaller_ondewo_nlu_ValidateEmbeddedRegexResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.ValidateEmbeddedRegexResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.CleanAllIntentsRequest> __Marshaller_ondewo_nlu_CleanAllIntentsRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.CleanAllIntentsRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.CleanAllIntentsResponse> __Marshaller_ondewo_nlu_CleanAllIntentsResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.CleanAllIntentsResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.CleanIntentRequest> __Marshaller_ondewo_nlu_CleanIntentRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.CleanIntentRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.CleanIntentResponse> __Marshaller_ondewo_nlu_CleanIntentResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.CleanIntentResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.CleanAllEntityTypesRequest> __Marshaller_ondewo_nlu_CleanAllEntityTypesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.CleanAllEntityTypesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.CleanAllEntityTypesResponse> __Marshaller_ondewo_nlu_CleanAllEntityTypesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.CleanAllEntityTypesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.CleanEntityTypeRequest> __Marshaller_ondewo_nlu_CleanEntityTypeRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.CleanEntityTypeRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.CleanEntityTypeResponse> __Marshaller_ondewo_nlu_CleanEntityTypeResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.CleanEntityTypeResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.AddTrainingPhrasesRequest> __Marshaller_ondewo_nlu_AddTrainingPhrasesRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.AddTrainingPhrasesRequest.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.AddTrainingPhrasesResponse> __Marshaller_ondewo_nlu_AddTrainingPhrasesResponse = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.AddTrainingPhrasesResponse.Parser));
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Marshaller<global::Ondewo.Nlu.AddTrainingPhrasesFromCSVRequest> __Marshaller_ondewo_nlu_AddTrainingPhrasesFromCSVRequest = grpc::Marshallers.Create(__Helper_SerializeMessage, context => __Helper_DeserializeMessage(context, global::Ondewo.Nlu.AddTrainingPhrasesFromCSVRequest.Parser));

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.ValidateRegexRequest, global::Ondewo.Nlu.ValidateRegexResponse> __Method_ValidateRegex = new grpc::Method<global::Ondewo.Nlu.ValidateRegexRequest, global::Ondewo.Nlu.ValidateRegexResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ValidateRegex",
        __Marshaller_ondewo_nlu_ValidateRegexRequest,
        __Marshaller_ondewo_nlu_ValidateRegexResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.ValidateEmbeddedRegexRequest, global::Ondewo.Nlu.ValidateEmbeddedRegexResponse> __Method_ValidateEmbeddedRegex = new grpc::Method<global::Ondewo.Nlu.ValidateEmbeddedRegexRequest, global::Ondewo.Nlu.ValidateEmbeddedRegexResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "ValidateEmbeddedRegex",
        __Marshaller_ondewo_nlu_ValidateEmbeddedRegexRequest,
        __Marshaller_ondewo_nlu_ValidateEmbeddedRegexResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.CleanAllIntentsRequest, global::Ondewo.Nlu.CleanAllIntentsResponse> __Method_CleanAllIntents = new grpc::Method<global::Ondewo.Nlu.CleanAllIntentsRequest, global::Ondewo.Nlu.CleanAllIntentsResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CleanAllIntents",
        __Marshaller_ondewo_nlu_CleanAllIntentsRequest,
        __Marshaller_ondewo_nlu_CleanAllIntentsResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.CleanIntentRequest, global::Ondewo.Nlu.CleanIntentResponse> __Method_CleanIntent = new grpc::Method<global::Ondewo.Nlu.CleanIntentRequest, global::Ondewo.Nlu.CleanIntentResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CleanIntent",
        __Marshaller_ondewo_nlu_CleanIntentRequest,
        __Marshaller_ondewo_nlu_CleanIntentResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.CleanAllEntityTypesRequest, global::Ondewo.Nlu.CleanAllEntityTypesResponse> __Method_CleanAllEntityTypes = new grpc::Method<global::Ondewo.Nlu.CleanAllEntityTypesRequest, global::Ondewo.Nlu.CleanAllEntityTypesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CleanAllEntityTypes",
        __Marshaller_ondewo_nlu_CleanAllEntityTypesRequest,
        __Marshaller_ondewo_nlu_CleanAllEntityTypesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.CleanEntityTypeRequest, global::Ondewo.Nlu.CleanEntityTypeResponse> __Method_CleanEntityType = new grpc::Method<global::Ondewo.Nlu.CleanEntityTypeRequest, global::Ondewo.Nlu.CleanEntityTypeResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "CleanEntityType",
        __Marshaller_ondewo_nlu_CleanEntityTypeRequest,
        __Marshaller_ondewo_nlu_CleanEntityTypeResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.AddTrainingPhrasesRequest, global::Ondewo.Nlu.AddTrainingPhrasesResponse> __Method_AddTrainingPhrases = new grpc::Method<global::Ondewo.Nlu.AddTrainingPhrasesRequest, global::Ondewo.Nlu.AddTrainingPhrasesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddTrainingPhrases",
        __Marshaller_ondewo_nlu_AddTrainingPhrasesRequest,
        __Marshaller_ondewo_nlu_AddTrainingPhrasesResponse);

    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    static readonly grpc::Method<global::Ondewo.Nlu.AddTrainingPhrasesFromCSVRequest, global::Ondewo.Nlu.AddTrainingPhrasesResponse> __Method_AddTrainingPhrasesFromCSV = new grpc::Method<global::Ondewo.Nlu.AddTrainingPhrasesFromCSVRequest, global::Ondewo.Nlu.AddTrainingPhrasesResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "AddTrainingPhrasesFromCSV",
        __Marshaller_ondewo_nlu_AddTrainingPhrasesFromCSVRequest,
        __Marshaller_ondewo_nlu_AddTrainingPhrasesResponse);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Ondewo.Nlu.UtilityReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Utilities</summary>
    [grpc::BindServiceMethod(typeof(Utilities), "BindService")]
    public abstract partial class UtilitiesBase
    {
      /// <summary>
      /// Validates the validity of python regexes
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.ValidateRegexResponse> ValidateRegex(global::Ondewo.Nlu.ValidateRegexRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Validate that entity types with group references have synonyms with
      /// capturing groups.
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.ValidateEmbeddedRegexResponse> ValidateEmbeddedRegex(global::Ondewo.Nlu.ValidateEmbeddedRegexRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Cleans all intent training phrases and entity annotations of parent
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.CleanAllIntentsResponse> CleanAllIntents(global::Ondewo.Nlu.CleanAllIntentsRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Cleans single intent training phrases and entity annotations
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.CleanIntentResponse> CleanIntent(global::Ondewo.Nlu.CleanIntentRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Cleans all entity types of parent
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.CleanAllEntityTypesResponse> CleanAllEntityTypes(global::Ondewo.Nlu.CleanAllEntityTypesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Cleans entity type
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.CleanEntityTypeResponse> CleanEntityType(global::Ondewo.Nlu.CleanEntityTypeRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Creates new training phrases corresponding to intent specified by its intent display name
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.AddTrainingPhrasesResponse> AddTrainingPhrases(global::Ondewo.Nlu.AddTrainingPhrasesRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// Creates new training phrases corresponding to intent specified by its intent display name from csv file
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::System.Threading.Tasks.Task<global::Ondewo.Nlu.AddTrainingPhrasesResponse> AddTrainingPhrasesFromCSV(global::Ondewo.Nlu.AddTrainingPhrasesFromCSVRequest request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Utilities</summary>
    public partial class UtilitiesClient : grpc::ClientBase<UtilitiesClient>
    {
      /// <summary>Creates a new client for Utilities</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public UtilitiesClient(grpc::ChannelBase channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Utilities that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public UtilitiesClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected UtilitiesClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected UtilitiesClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// Validates the validity of python regexes
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.ValidateRegexResponse ValidateRegex(global::Ondewo.Nlu.ValidateRegexRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ValidateRegex(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Validates the validity of python regexes
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.ValidateRegexResponse ValidateRegex(global::Ondewo.Nlu.ValidateRegexRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ValidateRegex, null, options, request);
      }
      /// <summary>
      /// Validates the validity of python regexes
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.ValidateRegexResponse> ValidateRegexAsync(global::Ondewo.Nlu.ValidateRegexRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ValidateRegexAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Validates the validity of python regexes
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.ValidateRegexResponse> ValidateRegexAsync(global::Ondewo.Nlu.ValidateRegexRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ValidateRegex, null, options, request);
      }
      /// <summary>
      /// Validate that entity types with group references have synonyms with
      /// capturing groups.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.ValidateEmbeddedRegexResponse ValidateEmbeddedRegex(global::Ondewo.Nlu.ValidateEmbeddedRegexRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ValidateEmbeddedRegex(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Validate that entity types with group references have synonyms with
      /// capturing groups.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.ValidateEmbeddedRegexResponse ValidateEmbeddedRegex(global::Ondewo.Nlu.ValidateEmbeddedRegexRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_ValidateEmbeddedRegex, null, options, request);
      }
      /// <summary>
      /// Validate that entity types with group references have synonyms with
      /// capturing groups.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.ValidateEmbeddedRegexResponse> ValidateEmbeddedRegexAsync(global::Ondewo.Nlu.ValidateEmbeddedRegexRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return ValidateEmbeddedRegexAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Validate that entity types with group references have synonyms with
      /// capturing groups.
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.ValidateEmbeddedRegexResponse> ValidateEmbeddedRegexAsync(global::Ondewo.Nlu.ValidateEmbeddedRegexRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_ValidateEmbeddedRegex, null, options, request);
      }
      /// <summary>
      /// Cleans all intent training phrases and entity annotations of parent
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.CleanAllIntentsResponse CleanAllIntents(global::Ondewo.Nlu.CleanAllIntentsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CleanAllIntents(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Cleans all intent training phrases and entity annotations of parent
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.CleanAllIntentsResponse CleanAllIntents(global::Ondewo.Nlu.CleanAllIntentsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CleanAllIntents, null, options, request);
      }
      /// <summary>
      /// Cleans all intent training phrases and entity annotations of parent
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.CleanAllIntentsResponse> CleanAllIntentsAsync(global::Ondewo.Nlu.CleanAllIntentsRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CleanAllIntentsAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Cleans all intent training phrases and entity annotations of parent
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.CleanAllIntentsResponse> CleanAllIntentsAsync(global::Ondewo.Nlu.CleanAllIntentsRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CleanAllIntents, null, options, request);
      }
      /// <summary>
      /// Cleans single intent training phrases and entity annotations
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.CleanIntentResponse CleanIntent(global::Ondewo.Nlu.CleanIntentRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CleanIntent(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Cleans single intent training phrases and entity annotations
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.CleanIntentResponse CleanIntent(global::Ondewo.Nlu.CleanIntentRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CleanIntent, null, options, request);
      }
      /// <summary>
      /// Cleans single intent training phrases and entity annotations
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.CleanIntentResponse> CleanIntentAsync(global::Ondewo.Nlu.CleanIntentRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CleanIntentAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Cleans single intent training phrases and entity annotations
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.CleanIntentResponse> CleanIntentAsync(global::Ondewo.Nlu.CleanIntentRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CleanIntent, null, options, request);
      }
      /// <summary>
      /// Cleans all entity types of parent
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.CleanAllEntityTypesResponse CleanAllEntityTypes(global::Ondewo.Nlu.CleanAllEntityTypesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CleanAllEntityTypes(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Cleans all entity types of parent
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.CleanAllEntityTypesResponse CleanAllEntityTypes(global::Ondewo.Nlu.CleanAllEntityTypesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CleanAllEntityTypes, null, options, request);
      }
      /// <summary>
      /// Cleans all entity types of parent
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.CleanAllEntityTypesResponse> CleanAllEntityTypesAsync(global::Ondewo.Nlu.CleanAllEntityTypesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CleanAllEntityTypesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Cleans all entity types of parent
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.CleanAllEntityTypesResponse> CleanAllEntityTypesAsync(global::Ondewo.Nlu.CleanAllEntityTypesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CleanAllEntityTypes, null, options, request);
      }
      /// <summary>
      /// Cleans entity type
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.CleanEntityTypeResponse CleanEntityType(global::Ondewo.Nlu.CleanEntityTypeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CleanEntityType(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Cleans entity type
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.CleanEntityTypeResponse CleanEntityType(global::Ondewo.Nlu.CleanEntityTypeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_CleanEntityType, null, options, request);
      }
      /// <summary>
      /// Cleans entity type
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.CleanEntityTypeResponse> CleanEntityTypeAsync(global::Ondewo.Nlu.CleanEntityTypeRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return CleanEntityTypeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Cleans entity type
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.CleanEntityTypeResponse> CleanEntityTypeAsync(global::Ondewo.Nlu.CleanEntityTypeRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_CleanEntityType, null, options, request);
      }
      /// <summary>
      /// Creates new training phrases corresponding to intent specified by its intent display name
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.AddTrainingPhrasesResponse AddTrainingPhrases(global::Ondewo.Nlu.AddTrainingPhrasesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddTrainingPhrases(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Creates new training phrases corresponding to intent specified by its intent display name
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.AddTrainingPhrasesResponse AddTrainingPhrases(global::Ondewo.Nlu.AddTrainingPhrasesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddTrainingPhrases, null, options, request);
      }
      /// <summary>
      /// Creates new training phrases corresponding to intent specified by its intent display name
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.AddTrainingPhrasesResponse> AddTrainingPhrasesAsync(global::Ondewo.Nlu.AddTrainingPhrasesRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddTrainingPhrasesAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Creates new training phrases corresponding to intent specified by its intent display name
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.AddTrainingPhrasesResponse> AddTrainingPhrasesAsync(global::Ondewo.Nlu.AddTrainingPhrasesRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddTrainingPhrases, null, options, request);
      }
      /// <summary>
      /// Creates new training phrases corresponding to intent specified by its intent display name from csv file
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.AddTrainingPhrasesResponse AddTrainingPhrasesFromCSV(global::Ondewo.Nlu.AddTrainingPhrasesFromCSVRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddTrainingPhrasesFromCSV(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Creates new training phrases corresponding to intent specified by its intent display name from csv file
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual global::Ondewo.Nlu.AddTrainingPhrasesResponse AddTrainingPhrasesFromCSV(global::Ondewo.Nlu.AddTrainingPhrasesFromCSVRequest request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_AddTrainingPhrasesFromCSV, null, options, request);
      }
      /// <summary>
      /// Creates new training phrases corresponding to intent specified by its intent display name from csv file
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.AddTrainingPhrasesResponse> AddTrainingPhrasesFromCSVAsync(global::Ondewo.Nlu.AddTrainingPhrasesFromCSVRequest request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return AddTrainingPhrasesFromCSVAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// Creates new training phrases corresponding to intent specified by its intent display name from csv file
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      public virtual grpc::AsyncUnaryCall<global::Ondewo.Nlu.AddTrainingPhrasesResponse> AddTrainingPhrasesFromCSVAsync(global::Ondewo.Nlu.AddTrainingPhrasesFromCSVRequest request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_AddTrainingPhrasesFromCSV, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
      protected override UtilitiesClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new UtilitiesClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static grpc::ServerServiceDefinition BindService(UtilitiesBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_ValidateRegex, serviceImpl.ValidateRegex)
          .AddMethod(__Method_ValidateEmbeddedRegex, serviceImpl.ValidateEmbeddedRegex)
          .AddMethod(__Method_CleanAllIntents, serviceImpl.CleanAllIntents)
          .AddMethod(__Method_CleanIntent, serviceImpl.CleanIntent)
          .AddMethod(__Method_CleanAllEntityTypes, serviceImpl.CleanAllEntityTypes)
          .AddMethod(__Method_CleanEntityType, serviceImpl.CleanEntityType)
          .AddMethod(__Method_AddTrainingPhrases, serviceImpl.AddTrainingPhrases)
          .AddMethod(__Method_AddTrainingPhrasesFromCSV, serviceImpl.AddTrainingPhrasesFromCSV).Build();
    }

    /// <summary>Register service method with a service binder with or without implementation. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    [global::System.CodeDom.Compiler.GeneratedCode("grpc_csharp_plugin", null)]
    public static void BindService(grpc::ServiceBinderBase serviceBinder, UtilitiesBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_ValidateRegex, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.ValidateRegexRequest, global::Ondewo.Nlu.ValidateRegexResponse>(serviceImpl.ValidateRegex));
      serviceBinder.AddMethod(__Method_ValidateEmbeddedRegex, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.ValidateEmbeddedRegexRequest, global::Ondewo.Nlu.ValidateEmbeddedRegexResponse>(serviceImpl.ValidateEmbeddedRegex));
      serviceBinder.AddMethod(__Method_CleanAllIntents, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.CleanAllIntentsRequest, global::Ondewo.Nlu.CleanAllIntentsResponse>(serviceImpl.CleanAllIntents));
      serviceBinder.AddMethod(__Method_CleanIntent, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.CleanIntentRequest, global::Ondewo.Nlu.CleanIntentResponse>(serviceImpl.CleanIntent));
      serviceBinder.AddMethod(__Method_CleanAllEntityTypes, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.CleanAllEntityTypesRequest, global::Ondewo.Nlu.CleanAllEntityTypesResponse>(serviceImpl.CleanAllEntityTypes));
      serviceBinder.AddMethod(__Method_CleanEntityType, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.CleanEntityTypeRequest, global::Ondewo.Nlu.CleanEntityTypeResponse>(serviceImpl.CleanEntityType));
      serviceBinder.AddMethod(__Method_AddTrainingPhrases, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.AddTrainingPhrasesRequest, global::Ondewo.Nlu.AddTrainingPhrasesResponse>(serviceImpl.AddTrainingPhrases));
      serviceBinder.AddMethod(__Method_AddTrainingPhrasesFromCSV, serviceImpl == null ? null : new grpc::UnaryServerMethod<global::Ondewo.Nlu.AddTrainingPhrasesFromCSVRequest, global::Ondewo.Nlu.AddTrainingPhrasesResponse>(serviceImpl.AddTrainingPhrasesFromCSV));
    }

  }
}
#endregion
